version: 2
sources:
  - name: pudl
    tables:
      - name: out_rus12__monthly_demand_and_energy_at_power_sources
        data_tests:
          - check_row_counts_per_partition:
              arguments:
                table_name: out_rus12__monthly_demand_and_energy_at_power_sources
                partition_expr: "EXTRACT(YEAR FROM report_date)"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: state
          - name: energy_output_mwh
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: peak_demand_mw
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: is_peak_coincident
          - name: peak_demand_date
          - name: peak_demand_hour
