"""Load pre-processed SEC 10-K assets from Google Cloud Storage.

These "raw" tables are generated by the SEC 10-K data extraction pipeline which can be
found in this repository: https://github.com/catalyst-cooperative/mozilla-sec-eia

However, the GCS bucket containing the data is not public, so these assets cannot be
loaded by a normal user. To address this issue we need to pull them into the same
Zenodo archiving system we use for all of our other inputs. See:
https://github.com/catalyst-cooperative/pudl/issues/4065
"""

import dagster as dg
import pandas as pd


def _load_table_from_gcs(table_name: str) -> pd.DataFrame:
    return pd.read_parquet(f"gs://model-outputs.catalyst.coop/sec10k/{table_name}")


@dg.asset(group_name="raw_sec10k")
def raw_sec10k__quarterly_filings() -> pd.DataFrame:
    """Metadata of all SEC 10-K filings."""
    return _load_table_from_gcs("core_sec10k__filings")


@dg.asset(group_name="raw_sec10k")
def raw_sec10k__quarterly_company_information() -> pd.DataFrame:
    """Company information extracted from the text headers of SEC 10-K filings."""
    return _load_table_from_gcs("core_sec10k__company_information")


@dg.asset(group_name="raw_sec10k")
def raw_sec10k__parents_and_subsidiaries() -> pd.DataFrame:
    """Parent/subsidiary relationships inferred from SEC 10-K filing data."""
    return _load_table_from_gcs("out_sec10k__parents_and_subsidiaries")


@dg.asset(group_name="raw_sec10k")
def raw_sec10k__exhibit_21_company_ownership() -> pd.DataFrame:
    """Subsidiary ownership information extracted from SEC 10-K Exhibit 21.

    Exhibit 21 is an unstructured text or PDF attachment to the main SEC 10-K filing
    that is used to describe the subsidiaries owned by the filing company.
    """
    return _load_table_from_gcs("core_sec10k__exhibit_21_company_ownership")
