version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia860__assn_boiler_cooling
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - data_maturity
                pk_table_name: source('pudl', 'core_pudl__codes_data_maturities')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                  - boiler_id
                  - report_date
                pk_table_name: source('pudl', 'core_eia860__scd_boilers')
                pk_column_names:
                  - plant_id_eia
                  - boiler_id
                  - report_date
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_eia860__assn_boiler_cooling
                partition_expr: EXTRACT(YEAR FROM report_date)
        columns:
          - name: report_date
          - name: plant_id_eia
          - name: boiler_id
          - name: cooling_id_eia
          - name: data_maturity
