---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /builds
    target-branch: main
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /.devcontainer
    target-branch: main
    schedule:
      interval: weekly
