---
changelog:
  exclude:
    authors:
      - catalyst-workflow-triggerer
      - catalyst-workflow-triggerer[bot]
      - dependabot
      - dependabot[bot]
      - pre-commit-ci
      - pre-commit-ci[bot]
      - pudlbot
    labels:
      - conda-lock
      - dependencies
  categories:
    - title: New & Updated Data
      labels:
        - new-data
        - data-update
    - title: Other Changes
      labels:
        - "*"
