version: 2
sources:
  - name: pudl
    tables:
      - name: out_rus12__yearly_plant_factors_and_maximum_demand
        data_tests:
          - check_row_counts_per_partition:
              arguments:
                table_name: out_rus12__yearly_plant_factors_and_maximum_demand
                partition_expr: "EXTRACT(YEAR FROM report_date)"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: state
          - name: plant_name_rus
          - name: plant_type
          - name: capacity_factor
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                    max_value: 1.0
                  config:
                    error_if: ">13" # Investigate 13 instances of cap fac > 1 for nuclear plants
          - name: capacity_factor_running
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                    max_value: 1.0
                  config:
                    error_if: ">121" # Investigate 121 instances of cap fac running > 1
          - name: load_factor
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                    max_value: 1.0
                  config:
                    error_if: ">2" # Investigate 2 instances of load fac > 1
          - name: peak_gross_demand_mw
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: peak_gross_demand_nameplate_mw
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
