version: 2
sources:
  - name: pudl
    tables:
      - name: out_ferc1__yearly_depreciation_factors_sched336
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_ferc1
                pk_table_name: source('pudl', 'core_pudl__assn_ferc1_pudl_utilities')
                pk_column_names:
                  - utility_id_ferc1
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_utilities_pudl')
                pk_column_names:
                  - utility_id_pudl
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: report_year
        columns:
          - name: record_id
          - name: report_year
          - name: utility_id_ferc1
          - name: utility_id_ferc1_dbf
          - name: utility_id_ferc1_xbrl
          - name: utility_id_pudl
          - name: utility_name_ferc1
          - name: depreciation_factors
          - name: depreciable_plant_base
          - name: net_salvage_pct
          - name: depreciation_rate
          - name: mortality_curve_type
          - name: order_num
          - name: account_num
          - name: service_life_avg
          - name: remaining_life_avg
