version: 2
sources:
  - name: pudl
    tables:
      - name: core_rus__codes_fuel_types
        data_tests:
          - expect_columns_not_all_null
        columns:
          - name: code
          - name: description
        meta:
          external_location: "{{ env_var('PUDL_PARQUET_BASE_PATH', env_var('PUDL_OUTPUT') ~ '/parquet') }}/core_rus__codes_fuel_types.parquet"
