version: 2
sources:
  - name: pudl
    tables:
      - name: core_rus7__yearly_external_financial_risk_ratio
        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_rus12__yearly_encumbrance_ratio
                partition_expr: "EXTRACT(YEAR FROM report_date)"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: external_financial_risk_ratio
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">18" # TODO: Investigate negative original loan amount values
