version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia176__yearly_company_characteristics

        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_eia176__yearly_company_characteristics
                partition_expr: "report_year"

        columns:
          - name: report_year
            data_tests:
              - not_null
          - name: operator_id_eia
            data_tests:
              - not_null
          - name: operating_state
            data_tests:
              - not_null
          - name: is_distribution_company_cooperative
            data_tests:
              - not_null
          - name: is_distribution_company_investor_owned
            data_tests:
              - not_null
          - name: is_distribution_company_municipally_owned
            data_tests:
              - not_null
          - name: is_distribution_company_privately_owned
            data_tests:
              - not_null
          - name: is_gatherer
            data_tests:
              - not_null
          - name: is_interstate_pipeline
            data_tests:
              - not_null
          - name: is_intrastate_pipeline
            data_tests:
              - not_null
          - name: is_liquid_natural_gas_marine_terminal
            data_tests:
              - not_null
          - name: is_liquid_natural_gas_peak_facility_operator
            data_tests:
              - not_null
          - name: is_producer
            data_tests:
              - not_null
          - name: is_storage_operator
            data_tests:
              - not_null
          - name: is_synthetic_natural_gas_plant_operator
            data_tests:
              - not_null
          - name: is_other_ownership
            data_tests:
              - not_null
          - name: other_ownership_description
          - name: has_alternative_fuel_fleet
          - name: is_public_compressed_natural_gas_fueling_station
            data_tests:
              - not_null
          - name: is_public_lng_fueling_station
            data_tests:
              - not_null
