version: 2
sources:
  - name: pudl
    tables:
      - name: core_pudl__assn_eia_pudl_plants
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_plants_pudl')
                pk_column_names:
                  - plant_id_pudl
          - expect_columns_not_all_null
          - check_row_counts_per_partition
        columns:
          - name: plant_id_eia
          - name: plant_name_eia
          - name: plant_id_pudl
