version: 2
sources:
  - name: pudl
    tables:
      - name: _core_eia__forensics_entity_resolution_generators
        columns:
          - name: plant_id_eia
          - name: generator_id
          - name: report_date
          - name: valid_until_date
          - name: column_name
          - name: record_value
          - name: entity_occurrences
          - name: record_occurrences
          - name: consistent_rate
          - name: is_candidate
