version: 2
sources:
  - name: pudl
    tables:
      - name: core_rus7__yearly_materials_and_supplies
        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_rus7__yearly_materials_and_supplies
                partition_expr: "EXTRACT(YEAR FROM report_date)"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: state
          - name: electric_or_other_materials
          - name: materials_adjustment
          - name: materials_ending_balance
          - name: materials_purchased
          - name: materials_salvaged
          - name: materials_sold
          - name: materials_used
