version: 2
sources:
  - name: pudl
    tables:
      - name: out_rus7__yearly_materials_and_supplies
        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: out_rus7__yearly_materials_and_supplies
                partition_expr: "EXTRACT(YEAR FROM report_date)"
          - dbt_utils.expression_is_true:
              arguments:
                expression: materials_purchased + materials_salvaged - materials_sold - materials_used + materials_adjustment <= materials_ending_balance
              description: "Check that annual changes don't exceed ending balance."
              config:
                error_if: ">3"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: state
          - name: electric_or_other_materials
          - name: materials_adjustment
          - name: materials_ending_balance
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">12"
          - name: materials_purchased
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">2"
          - name: materials_salvaged
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">16"
          - name: materials_sold
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">7"
          - name: materials_used
            data_tests:
              - dbt_expectations.expect_column_values_to_be_between:
                  arguments:
                    min_value: 0.0
                  config:
                    error_if: ">4"
