"""Define dbt schema types and merging logic.

We generate dbt schema.yml files by translating our metadata into schema.yml
format, then applying human-sourced patches to the auto-generated schemas.
"""

from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

from pudl.metadata.classes import PUDL_PACKAGE


def _prettier_yaml_dumps(yaml_contents: dict[str, Any]) -> str:
    """Dump YAML to string that Prettier likes."""

    class PrettierCompatibleDumper(yaml.Dumper):
        """Custom Dumper that indents lists like prettier does.

        Default dumper behavior::

            foo:
            - name: a
            - name: b

        prettier behavior::

            foo:
              - name: a
              - name: b

        NOTE (2025-07-10): this code was generated by LLM and Does The
        Right Thing. It appears to do so by forcing the ``indentless`` parameter to
        always be ``False``. If at any point this stops working we should convert
        to using ``ruamel`` which has much more customizable formatting with actual
        documentation.
        """

        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    return yaml.dump(
        yaml_contents,
        default_flow_style=False,
        Dumper=PrettierCompatibleDumper,
        indent=2,
        sort_keys=False,
        width=float("inf"),
    )


class DbtColumn(BaseModel):
    """Define yaml structure of a dbt column."""

    name: str
    description: str | None = None
    data_tests: list | None = None
    meta: dict | None = None
    tags: list[str] | None = None


class DbtTable(BaseModel):
    """Define yaml structure of a dbt table."""

    name: str
    description: str | None = None
    data_tests: list | None = None
    columns: list[DbtColumn] | None = None
    meta: dict | None = None
    tags: list[str] | None = None
    config: dict | None = None  # only for models

    @classmethod
    def from_table_name(cls, table_name: str) -> "DbtTable":
        """Construct configuration defining table from PUDL metadata."""
        return cls(
            name=table_name,
            columns=[
                DbtColumn(name=f.name)
                for f in PUDL_PACKAGE.get_resource(table_name).schema.fields
            ],
        )


class DbtSource(BaseModel):
    """Define basic dbt yml structure to add a pudl table as a dbt source."""

    name: str = "pudl"
    tables: list[DbtTable] | None = None
    description: str | None = None
    meta: dict | None = None


class DbtSchema(BaseModel):
    """Define basic structure of a dbt models yaml file."""

    version: int = 2
    sources: list[DbtSource] | None = None
    models: list[DbtTable] | None = None

    @classmethod
    def from_table_name(cls, table_name: str) -> "DbtSchema":
        """Construct configuration defining table from PUDL metadata."""
        return cls(
            sources=[
                DbtSource(
                    tables=[DbtTable.from_table_name(table_name)],
                )
            ],
        )

    @classmethod
    def from_yaml(cls, schema_path: Path) -> "DbtSchema":
        """Load a DbtSchema object from a YAML file."""
        with schema_path.open("r") as schema_yaml:
            return cls.model_validate(yaml.safe_load(schema_yaml))

    def to_yaml(self, schema_path: Path):
        """Write DbtSchema object to YAML file."""
        with schema_path.open("w") as schema_file:
            yaml_output = _prettier_yaml_dumps(self.model_dump(exclude_none=True))
            schema_file.write(yaml_output)

    def validate_humanity(self):
        """Make sure the human schema matches expectations.

        We expect that any source tables only have data tests or column-level data tests as human overrides.
        We allow the 'name' field so we can match human tables/columns with machine ones.

        We do not have any expectations about model definitions since those are human-only.
        """
        table_whitelist = {"name", "data_tests", "columns"}
        column_whitelist = {"name", "data_tests"}
        for source in self.sources or []:
            for table in source.tables or []:
                existing_keys = set(table.model_dump(exclude_defaults=True).keys())
                invalid_keys = existing_keys - table_whitelist
                assert len(invalid_keys) == 0, (
                    f"Found {invalid_keys=} in human version of {table.name}"
                )
                for column in table.columns or []:
                    existing_colkeys = set(
                        column.model_dump(exclude_defaults=True).keys()
                    )
                    invalid_colkeys = existing_colkeys - column_whitelist
                    assert len(invalid_colkeys) == 0, (
                        f"Found {invalid_colkeys=} in human version of {table.name}:{column.name}"
                    )


def merge_schema(machine_schema: DbtSchema, human_schema: DbtSchema) -> DbtSchema:
    """Apply human-schema as patch to machine-schema.

    If merged sources are empty list, pass None so we don't serialize them.
    """
    human_schema.validate_humanity()
    merged_sources = merge_sources_by_name(
        machine_schema.sources or [], human_schema.sources or []
    )
    # NOTE 2026-05-11: all models are human-generated.
    return DbtSchema(sources=merged_sources or None, models=human_schema.models)


def merge_by_name(
    machine_elements: list,
    human_elements: list,
    merger: Callable,
    element_factory: Callable,
) -> list:
    """Merge two lists of dbt elements, matching by name.

    Args:
        machine_elements: can be empty list.
        human_elements: can also be empty list.
        merger: this takes two elements of the same dbt type (source, table,
            column) and returns a third element that is the merged version.
        element_factory: this takes the element name and returns an empty instance - used if e.g. the human element doesn't exist.
    """
    human_elements_by_name = {element.name: element for element in human_elements}

    return [
        merger(
            machine_element,
            human_elements_by_name.get(
                machine_element.name, element_factory(name=machine_element.name)
            ),
        )
        for machine_element in machine_elements
    ]


def merge_sources_by_name(
    machine_sources: list[DbtSource], human_sources: list[DbtSource]
) -> list[DbtSource]:
    """Match machine/human sources by name, then merge them."""
    return merge_by_name(machine_sources, human_sources, merge_source, DbtSource)


def merge_source(machine_source: DbtSource, human_source: DbtSource) -> DbtSource:
    """Apply human source def as patch on top of machine source.

    * make a deep-copy to avoid aliasing issues
    * merge the tables
    """
    return machine_source.model_copy(
        deep=True,
        update={
            "tables": merge_tables_by_name(
                machine_source.tables or [], human_source.tables or []
            )
        },
    )


def merge_tables_by_name(
    machine_tables: list[DbtTable], human_tables: list[DbtTable]
) -> list[DbtTable]:
    """Match machine/human tables by name, then merge them."""
    return merge_by_name(machine_tables, human_tables, merge_table, DbtTable)


def merge_table(machine_table: DbtTable, human_table: DbtTable) -> DbtTable:
    """Apply human table def as patch on machine table def.

    * make a deep-copy to avoid aliasing issues
    * merge the data tests
    * merge the columns
    """
    merged_data_tests = (machine_table.data_tests or []) + (
        human_table.data_tests or []
    )
    return machine_table.model_copy(
        deep=True,
        update={
            "data_tests": merged_data_tests or None,
            "columns": merge_columns_by_name(
                machine_table.columns or [], human_table.columns or []
            ),
        },
    )


def merge_columns_by_name(
    machine_columns: list[DbtColumn], human_columns: list[DbtColumn]
) -> list[DbtColumn]:
    """Match machine/human columns by name, then merge them."""
    return merge_by_name(machine_columns, human_columns, merge_column, DbtColumn)


def merge_column(machine_column: DbtColumn, human_column: DbtColumn) -> DbtColumn:
    """Apply human column def as patch on machine column def.

    * make a deep-copy to avoid aliasing issues
    * merge the data tests
    * don't update anything else like descriptions etc.
    """
    merged_data_tests = (machine_column.data_tests or []) + (
        human_column.data_tests or []
    )
    return machine_column.model_copy(
        deep=True,
        update={"data_tests": merged_data_tests or None},
    )
