"""Merge machine-generated dbt schema files with sparse human overlays."""

from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

from pudl.metadata.classes import PUDL_PACKAGE


def _prettier_yaml_dumps(yaml_contents: dict[str, Any]) -> str:
    """Dump YAML to string that Prettier likes."""

    class PrettierCompatibleDumper(yaml.Dumper):
        """Custom Dumper that indents lists like prettier does.

        Default dumper behavior::

            foo:
            - name: a
            - name: b

        prettier behavior::

            foo:
              - name: a
              - name: b

        NOTE (2025-07-10): this code was generated by LLM and Does The
        Right Thing. It appears to do so by forcing the ``indentless`` parameter to
        always be ``False``. If at any point this stops working we should convert
        to using ``ruamel`` which has much more customizable formatting with actual
        documentation.
        """

        def increase_indent(self, flow=False, indentless=False):
            return super().increase_indent(flow, False)

    return yaml.dump(
        yaml_contents,
        default_flow_style=False,
        Dumper=PrettierCompatibleDumper,
        indent=2,
        sort_keys=False,
        width=float("inf"),
    )


class DbtColumn(BaseModel):
    """Define yaml structure of a dbt column."""

    name: str
    description: str | None = None
    data_tests: list | None = None
    meta: dict | None = None
    tags: list[str] | None = None


class DbtTable(BaseModel):
    """Define yaml structure of a dbt table."""

    name: str
    description: str | None = None
    data_tests: list | None = None
    columns: list[DbtColumn] | None = None
    meta: dict | None = None
    tags: list[str] | None = None
    config: dict | None = None  # only for models

    @classmethod
    def from_table_name(cls, table_name: str) -> "DbtTable":
        """Construct configuration defining table from PUDL metadata."""
        return cls(
            name=table_name,
            columns=[
                DbtColumn(name=f.name)
                for f in PUDL_PACKAGE.get_resource(table_name).schema.fields
            ],
        )


class DbtSource(BaseModel):
    """Define basic dbt yml structure to add a pudl table as a dbt source."""

    name: str = "pudl"
    tables: list[DbtTable] | None = None
    description: str | None = None
    meta: dict | None = None


class DbtSchema(BaseModel):
    """Define basic structure of a dbt models yaml file."""

    version: int = 2
    sources: list[DbtSource] | None = None
    models: list[DbtTable] | None = None

    @classmethod
    def from_table_name(cls, table_name: str) -> "DbtSchema":
        """Construct configuration defining table from PUDL metadata."""
        return cls(
            sources=[
                DbtSource(
                    tables=[DbtTable.from_table_name(table_name)],
                )
            ],
        )

    @classmethod
    def from_yaml(cls, schema_path: Path) -> "DbtSchema":
        """Load a DbtSchema object from a YAML file."""
        with schema_path.open("r") as schema_yaml:
            return cls.model_validate(yaml.safe_load(schema_yaml))

    def to_yaml(self, schema_path: Path):
        """Write DbtSchema object to YAML file."""
        with schema_path.open("w") as schema_file:
            yaml_output = _prettier_yaml_dumps(self.model_dump(exclude_none=True))
            schema_file.write(yaml_output)


def merge_schema_paths(machine_path: Path, human_path: Path) -> DbtSchema:
    """Merge persisted machine/human schemas."""

    def _maybe_get_human_schema(human_path: Path) -> DbtSchema:
        if not human_path.exists():
            return DbtSchema()
        with human_path.open("r") as f:
            if f.read().strip() == "":
                return DbtSchema()
        return DbtSchema.from_yaml(human_path)

    human_schema = _maybe_get_human_schema(human_path)
    machine_schema = DbtSchema.from_yaml(machine_path)
    return merge_schema(machine_schema, human_schema)


def merge_schema(machine_schema: DbtSchema, human_schema: DbtSchema) -> DbtSchema:
    """Merge a machine schema file with a human overlay schema file.

    The machine schema defines the full dbt structure. The human schema is a
    sparse overlay whose matching entries patch the machine schema
    while preserving the machine inventory and ordering.
    """
    merged_sources = None
    if machine_schema.sources is not None:
        merged_sources = merge_sources(
            machine_schema.sources, human_schema.sources or []
        )
    elif human_schema.sources is not None:
        merged_sources = [
            source.model_copy(deep=True) for source in human_schema.sources
        ]

    if machine_schema.models:
        merged_models = merge_tables_by_name(
            machine_schema.models, human_schema.models or []
        )
    else:
        merged_models = (
            [model.model_copy(deep=True) for model in human_schema.models]
            if human_schema.models is not None
            else machine_schema.models
        )

    return DbtSchema(sources=merged_sources, models=merged_models)


def merge_sources(
    machine_sources: list[DbtSource], human_sources: list[DbtSource]
) -> list[DbtSource]:
    """Apply human source overlays to the matching machine sources.

    The merged result keeps the machine source list as the canonical inventory.
    Human sources behave as sparse patches that can update the tables contained
    in matching machine sources.
    """
    for human_source in human_sources:
        {source.name: source for source in machine_sources}[human_source.name]

    human_sources_by_name = {source.name: source for source in human_sources}

    return [
        merge_source(machine_source, human_sources_by_name[machine_source.name])
        if machine_source.name in human_sources_by_name
        else machine_source.model_copy(deep=True)
        for machine_source in machine_sources
    ]


def merge_source(machine_source: DbtSource, human_source: DbtSource) -> DbtSource:
    """Apply a human source overlay onto a machine-generated source.

    The machine source supplies the canonical structure and ordering. The human
    source acts as a sparse patch that can update the matching machine tables.
    """
    return machine_source.model_copy(
        deep=True,
        update={
            "tables": merge_tables_by_name(
                machine_source.tables or [], human_source.tables or []
            )
        },
    )


def merge_tables_by_name(
    machine_tables: list[DbtTable], human_tables: list[DbtTable]
) -> list[DbtTable]:
    """Apply human table overlays to the matching machine tables.

    The merged result preserves the machine table list and order. Only tables
    present in the human overlay are considered for merging.
    """
    for human_table in human_tables:
        {table.name: table for table in machine_tables}[human_table.name]

    human_tables_by_name = {table.name: table for table in human_tables}

    return [
        merge_table(machine_table, human_tables_by_name[machine_table.name])
        if machine_table.name in human_tables_by_name
        else machine_table.model_copy(deep=True)
        for machine_table in machine_tables
    ]


def merge_table(machine_table: DbtTable, human_table: DbtTable) -> DbtTable:
    """Apply a human table overlay onto a machine-generated table.

    The machine table supplies the canonical structure and ordering. The human
    table acts as a sparse patch that can add tests and column metadata for the
    corresponding machine table.
    """
    return machine_table.model_copy(
        deep=True,
        update={
            "data_tests": (machine_table.data_tests or [])
            + (human_table.data_tests or []),
            "columns": merge_columns(
                machine_table.columns or [], human_table.columns or []
            ),
        },
    )


def merge_columns(
    machine_columns: list[DbtColumn], human_columns: list[DbtColumn]
) -> list[DbtColumn]:
    """Apply human column overlays to the matching machine columns.

    The merged result preserves the machine column list and order. Only columns
    named in the human overlay are examined, and only matching machine columns
    are updated.
    """
    for human_column in human_columns:
        {column.name: column for column in machine_columns}[human_column.name]

    human_columns_by_name = {column.name: column for column in human_columns}

    return [
        merge_column(machine_column, human_columns_by_name[machine_column.name])
        if machine_column.name in human_columns_by_name
        else machine_column.model_copy(deep=True)
        for machine_column in machine_columns
    ]


def merge_column(machine_column: DbtColumn, human_column: DbtColumn) -> DbtColumn:
    """Apply a human column overlay onto a machine-generated column.

    The machine column supplies the canonical structure and ordering. The human
    column acts as a sparse patch that can add tests for the corresponding
    machine column.
    """
    return machine_column.model_copy(
        deep=True,
        update={
            "data_tests": (machine_column.data_tests or [])
            + (human_column.data_tests or [])
        },
    )
