version: 2
sources:
  - name: pudl
    tables:
      - name: out_eia923__monthly_generation_fuel_by_generator
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                  - generator_id
                pk_table_name: source('pudl', 'core_eia__entity_generators')
                pk_column_names:
                  - plant_id_eia
                  - generator_id
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_eia
                pk_table_name: source('pudl', 'core_eia__entity_utilities')
                pk_column_names:
                  - utility_id_eia
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_plants_pudl')
                pk_column_names:
                  - plant_id_pudl
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_utilities_pudl')
                pk_column_names:
                  - utility_id_pudl
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: EXTRACT(YEAR FROM report_date)
          - expect_date_frequency_ratio:
              arguments:
                compare_model: source("pudl", "out_eia__yearly_generators")
                multiplier: 12
                date_column: report_date
                model_has_data_maturity: false
        columns:
          - name: report_date
          - name: plant_id_eia
          - name: plant_id_pudl
          - name: plant_name_eia
          - name: utility_id_eia
          - name: utility_id_pudl
          - name: utility_name_eia
          - name: generator_id
          - name: unit_id_pudl
          - name: fuel_consumed_for_electricity_mmbtu
          - name: fuel_consumed_mmbtu
          - name: net_generation_mwh
