version: 2
sources:
  - name: pudl
    tables:
      - name: core_pudl__assn_utilities_plants
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_plants_pudl')
                pk_column_names:
                  - plant_id_pudl
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_utilities_pudl')
                pk_column_names:
                  - utility_id_pudl
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_pudl__assn_utilities_plants
                partition_expr: null
        columns:
          - name: utility_id_pudl
          - name: plant_id_pudl
            data_tests:
              - one_value_per_key:
                  arguments:
                    other_column_name: utility_id_pudl
                  description: |-
                    We expect each plant to only be assigned to one utility, but we still need to
                    deduplicate ID assignment. See issue 4988.
                  config:
                    severity: warn
