version: 2
sources:
  - name: pudl
    tables:
      - name: _core_phmsagas__yearly_distribution_by_install_decade
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - report_id
                  - report_date
                  - operator_id_phmsa
                pk_table_name: source('pudl', 'core_phmsagas__yearly_distribution_operators')
                pk_column_names:
                  - report_id
                  - report_date
                  - operator_id_phmsa
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: EXTRACT(YEAR FROM report_date)
        columns:
          - name: report_id
          - name: report_date
          - name: operator_id_phmsa
          - name: commodity
          - name: operating_state
          - name: install_decade
          - name: mains_miles
          - name: services
