version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia861__yearly_dynamic_pricing
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - data_maturity
                pk_table_name: source('pudl', 'core_pudl__codes_data_maturities')
                pk_column_names:
                  - code
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: EXTRACT(YEAR FROM report_date)
        columns:
          - name: balancing_authority_code_eia
          - name: critical_peak_pricing
          - name: critical_peak_rebate
          - name: customer_class
          - name: customers
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: real_time_pricing
          - name: report_date
          - name: short_form
          - name: state
          - name: time_of_use_pricing
          - name: utility_id_eia
          - name: utility_name_eia
          - name: variable_peak_pricing
          - name: data_maturity
