version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia923__monthly_generation_fuel_nuclear
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - data_maturity
                pk_table_name: source('pudl', 'core_pudl__codes_data_maturities')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - energy_source_code
                pk_table_name: source('pudl', 'core_eia__codes_energy_sources')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - fuel_type_code_agg
                pk_table_name: source('pudl', 'core_eia__codes_fuel_types_agg')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                pk_table_name: source('pudl', 'core_eia__entity_plants')
                pk_column_names:
                  - plant_id_eia
          - foreign_key:
              arguments:
                fk_column_names:
                  - prime_mover_code
                pk_table_name: source('pudl', 'core_eia__codes_prime_movers')
                pk_column_names:
                  - code
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_eia923__monthly_generation_fuel_nuclear
                partition_expr: EXTRACT(YEAR FROM report_date)
          - expect_nuclear_units_are_generators:
              arguments:
                generator_model: source('pudl', 'out_eia__yearly_generators')
        columns:
          - name: plant_id_eia
          - name: report_date
          - name: nuclear_unit_id
          - name: energy_source_code
          - name: fuel_type_code_pudl
            data_tests:
              - dbt_expectations.expect_column_values_to_be_in_set:
                  arguments:
                    value_set:
                      - nuclear
                      - oil
          - name: fuel_type_code_agg
          - name: prime_mover_code
          - name: fuel_consumed_units
          - name: fuel_consumed_for_electricity_units
          - name: fuel_mmbtu_per_unit
          - name: fuel_consumed_mmbtu
          - name: fuel_consumed_for_electricity_mmbtu
          - name: net_generation_mwh
            data_tests:
              - expect_column_fraction_with_condition:
                  arguments:
                    numerator_row_condition: fuel_type_code_pudl='nuclear'
                    min_fraction: 0.9999
                    max_fraction: 1.0
          - name: data_maturity
