version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia__entity_plants
        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition
        columns:
          - name: plant_id_eia
          - name: plant_name_eia
          - name: city
          - name: county
          - name: latitude
          - name: longitude
          - name: state
          - name: street_address
          - name: zip_code
          - name: timezone
        meta:
          external_location: "{{ env_var('PUDL_PARQUET_BASE_PATH', env_var('PUDL_OUTPUT') ~ '/parquet') }}/core_eia__entity_plants.parquet"
