version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia923__entity_coalmine
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - mine_type_code
                pk_table_name: source('pudl', 'core_eia__codes_coalmine_types')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - data_maturity
                pk_table_name: source('pudl', 'core_pudl__codes_data_maturities')
                pk_column_names:
                  - code
          - expect_columns_not_all_null:
              description: |-
                Because this is an entity table, it only describes attributes that are constant across
                time. However, the county FIPS code is only available in some reporting years. If one of
                those years is processed, then it is non-null in this table. If none of those years are
                processed, then it will be entirely null here, and there is no column that we can
                aggregate across to identify when it should be null or non-null, so it is excluded from
                the test.
              arguments:
                exclude_columns:
                  - county_id_fips
          - check_row_counts_per_partition
        columns:
          - name: mine_id_pudl
            data_tests:
              - not_null
              - unique
          - name: mine_name
            data_tests:
              - not_null
          - name: mine_type_code
          - name: state
            data_tests:
              - not_null
          - name: county_id_fips
          - name: mine_id_msha
          - name: data_maturity
            data_tests:
              - not_null
