version: 2
sources:
  - name: pudl
    tables:
      - name: core_rus12__yearly_demand_and_energy_at_delivery_points
        data_tests:
          - check_row_counts_per_partition:
              arguments:
                table_name: core_rus12__yearly_demand_and_energy_at_delivery_points
                partition_expr: "EXTRACT(YEAR FROM report_date)"
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: delivery_recipient
          - name: timeframe
          - name: delivered_demand_mw
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: delivered_energy_mwh
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
