"""Table definitions for the FERC EQR data group."""

from typing import Any

TABLE_DESCRIPTIONS = {
    "ident": {
        "additional_summary_text": "placeholder",
        "additional_source_text": "placeholder",
        "usage_warnings": [],
    },
    "contracts": {
        "additional_summary_text": "placeholder",
        "additional_source_text": "placeholder",
        "usage_warnings": [],
    },
    "transactions": {
        "additional_summary_text": "placeholder",
        "additional_source_text": "placeholder",
        "usage_warnings": [],
    },
    "index_pub": {
        "additional_summary_text": "placeholder",
        "additional_source_text": "placeholder",
        "usage_warnings": [],
    },
}

RESOURCE_METADATA: dict[str, dict[str, Any]] = {
    "core_ferceqr__identity": {
        "description": TABLE_DESCRIPTIONS["ident"],
        "schema": {
            "fields": [
                "filer_unique_id",
                "company_identifier",
                "company_name",
                "contact_name",
                "contact_title",
                "contact_address",
                "contact_city",
                "contact_state",
                "contact_zip",
                "contact_country_name",
                "contact_phone",
                "contact_email",
                "transactions_reported_to_index_price_publishers",
                "year_quarter",
            ],
        },
        "create_database_schema": False,
        "sources": ["ferceqr"],
        "etl_group": "ferceqr",
        "field_namespace": "ferceqr",
    },
    "core_ferceqr__contracts": {
        "description": TABLE_DESCRIPTIONS["contracts"],
        "schema": {
            "fields": [
                "year_quarter",
                "company_identifier",
                "contract_unique_id",
                "seller_company_name",
                "customer_company_name",
                "contract_affiliate",
                "ferc_tariff_reference",
                "contract_service_agreement_id",
                "contract_execution_date",
                "commencement_date_of_contract_term",
                "contract_termination_date",
                "actual_termination_date",
                "extension_provision_description",
                "class_name",
                "term_name",
                "increment_name",
                "increment_peaking_name",
                "product_type_name",
                "product_name",
                "quantity",
                "units",
                "rate",
                "rate_minimum",
                "rate_maximum",
                "rate_description",
                "rate_units",
                "point_of_receipt_balancing_authority",
                "point_of_receipt_specific_location",
                "point_of_delivery_balancing_authority",
                "point_of_delivery_specific_location",
                "begin_date",
                "end_date",
            ],
        },
        "create_database_schema": False,
        "sources": ["ferceqr"],
        "etl_group": "ferceqr",
        "field_namespace": "ferceqr",
    },
    "core_ferceqr__transactions": {
        "description": TABLE_DESCRIPTIONS["contracts"],
        "schema": {
            "fields": [
                "year_quarter",
                "company_identifier",
                "transaction_unique_id",
                "seller_company_name",
                "customer_company_name",
                "ferc_tariff_reference",
                "contract_service_agreement_id",
                "transaction_unique_identifier",
                "transaction_begin_date",
                "transaction_end_date",
                "trade_date",
                "exchange_brokerage_service",
                "type_of_rate",
                "timezone",
                "class_name",
                "term_name",
                "increment_name",
                "increment_peaking_name",
                "product_name",
                "rate_units",
                "point_of_delivery_balancing_authority",
                "point_of_delivery_specific_location",
                "transaction_quantity",
                "price",
                "standardized_quantity",
                "standardized_price",
                "total_transmission_charge",
                "total_transaction_charge",
            ],
        },
        "create_database_schema": False,
        "sources": ["ferceqr"],
        "etl_group": "ferceqr",
        "field_namespace": "ferceqr",
    },
}
