"""AER to MER

Revision ID: 08901b7bc357
Revises: 2c52a938f5cc
Create Date: 2024-07-19 12:06:47.896695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08901b7bc357'
down_revision = '2c52a938f5cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eia923__monthly_generation_fuel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_mer', sa.Text(), nullable=True, comment='A partial aggregation of the reported fuel type codes into larger categories used by EIA in, for example, the Monthly Energy Review (MER) (and former Annual Energy Review). Two or three letter alphanumeric.'))
        batch_op.drop_constraint('fk_core_eia923__monthly_generation_fuel_fuel_type_code_aer_core_eia__codes_fuel_types_aer', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_core_eia923__monthly_generation_fuel_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), 'core_eia__codes_fuel_types_aer', ['fuel_type_code_mer'], ['code'])
        batch_op.drop_column('fuel_type_code_aer')

    with op.batch_alter_table('core_eia923__monthly_generation_fuel_nuclear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_mer', sa.Text(), nullable=True, comment='A partial aggregation of the reported fuel type codes into larger categories used by EIA in, for example, the Monthly Energy Review (MER) (and former Annual Energy Review). Two or three letter alphanumeric.'))
        batch_op.drop_constraint('fk_core_eia923__monthly_generation_fuel_nuclear_fuel_type_code_aer_core_eia__codes_fuel_types_aer', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_core_eia923__monthly_generation_fuel_nuclear_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), 'core_eia__codes_fuel_types_aer', ['fuel_type_code_mer'], ['code'])
        batch_op.drop_column('fuel_type_code_aer')

    with op.batch_alter_table('out_eia923__generation_fuel_combined', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_mer', sa.Text(), nullable=True, comment='A partial aggregation of the reported fuel type codes into larger categories used by EIA in, for example, the Monthly Energy Review (MER) (and former Annual Energy Review). Two or three letter alphanumeric.'))
        batch_op.drop_constraint('fk_out_eia923__generation_fuel_combined_fuel_type_code_aer_core_eia__codes_fuel_types_aer', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_out_eia923__generation_fuel_combined_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), 'core_eia__codes_fuel_types_aer', ['fuel_type_code_mer'], ['code'])
        batch_op.drop_column('fuel_type_code_aer')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_eia923__generation_fuel_combined', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_aer', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_out_eia923__generation_fuel_combined_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), type_='foreignkey')
        batch_op.create_foreign_key('fk_out_eia923__generation_fuel_combined_fuel_type_code_aer_core_eia__codes_fuel_types_aer', 'core_eia__codes_fuel_types_aer', ['fuel_type_code_aer'], ['code'])
        batch_op.drop_column('fuel_type_code_mer')

    with op.batch_alter_table('core_eia923__monthly_generation_fuel_nuclear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_aer', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_core_eia923__monthly_generation_fuel_nuclear_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), type_='foreignkey')
        batch_op.create_foreign_key('fk_core_eia923__monthly_generation_fuel_nuclear_fuel_type_code_aer_core_eia__codes_fuel_types_aer', 'core_eia__codes_fuel_types_aer', ['fuel_type_code_aer'], ['code'])
        batch_op.drop_column('fuel_type_code_mer')

    with op.batch_alter_table('core_eia923__monthly_generation_fuel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuel_type_code_aer', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_core_eia923__monthly_generation_fuel_fuel_type_code_mer_core_eia__codes_fuel_types_aer'), type_='foreignkey')
        batch_op.create_foreign_key('fk_core_eia923__monthly_generation_fuel_fuel_type_code_aer_core_eia__codes_fuel_types_aer', 'core_eia__codes_fuel_types_aer', ['fuel_type_code_aer'], ['code'])
        batch_op.drop_column('fuel_type_code_mer')

    # ### end Alembic commands ###
