"""Fix 861 fk error.

Revision ID: 0e91945ccd7d
Revises: 43749fc01948
Create Date: 2023-05-15 12:59:45.704223
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e91945ccd7d"
down_revision = "43749fc01948"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "compiled_geometry_balancing_authority_eia861", schema=None
    ) as batch_op:
        batch_op.alter_column("county_id_fips", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("report_date", existing_type=sa.DATE(), nullable=False)
        batch_op.alter_column(
            "balancing_authority_id_eia", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("county", existing_type=sa.TEXT(), nullable=False)

    with op.batch_alter_table(
        "compiled_geometry_utility_eia861", schema=None
    ) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "utilities_entity_eia", ["utility_id_eia"], ["utility_id_eia"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "compiled_geometry_utility_eia861", schema=None
    ) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None,
            "utilities_eia860",
            ["utility_id_eia", "report_date"],
            ["utility_id_eia", "report_date"],
        )

    with op.batch_alter_table(
        "compiled_geometry_balancing_authority_eia861", schema=None
    ) as batch_op:
        batch_op.alter_column("county", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column(
            "balancing_authority_id_eia", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("report_date", existing_type=sa.DATE(), nullable=True)
        batch_op.alter_column("county_id_fips", existing_type=sa.TEXT(), nullable=True)

    # ### end Alembic commands ###
