"""Add core_eia176__yearly_liquefied_natural_gas_inventory

Revision ID: 19ec11f1ed95
Revises: 4f252e9e2ce3
Create Date: 2026-05-05 10:06:29.419910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ec11f1ed95'
down_revision = '4f252e9e2ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eia176__yearly_liquefied_natural_gas_inventory',
    sa.Column('operator_id_eia', sa.Text(), nullable=False, comment='The unique EIA identifier for an operator in a given state. The last two letters of the ID indicate the state.'),
    sa.Column('report_year', sa.Integer(), nullable=False, comment='Four-digit year in which the data was reported.'),
    sa.Column('operating_state', sa.Text(), nullable=True, comment='State that the distribution utility is reporting for. Prior to 2004, this may be a list of states.'),
    sa.Column('facility_type', sa.Enum('lng_terminal', 'marine_terminal'), nullable=False, comment='Type of liquefied natural gas storage facility reported in Part 5 of EIA Form 176.'),
    sa.Column('volume_mcf', sa.Float(), nullable=True, comment='Volume of liquefied natural gas inventory held in storage at the end of the report year. Reference conditions for measurement are 14.73 psia and 60° Fahrenheit.'),
    sa.Column('capacity_mmcfd', sa.Float(), nullable=True, comment='Daily deliverability capacity of a liquefied natural gas storage facility at the end of the report year.'),
    sa.PrimaryKeyConstraint('operator_id_eia', 'report_year', 'facility_type', name=op.f('pk_core_eia176__yearly_liquefied_natural_gas_inventory'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_eia176__yearly_liquefied_natural_gas_inventory')
    # ### end Alembic commands ###
