"""update core sec company info PK

Revision ID: 1eddd884c887
Revises: 60f1cd56406b
Create Date: 2025-05-29 10:39:28.159346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eddd884c887'
down_revision = '60f1cd56406b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('filer_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    with op.batch_alter_table('out_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('filer_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.alter_column('filer_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=True)
    with op.batch_alter_table('out_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.alter_column('filer_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
