"""update rus7 phase 3

Revision ID: 328b8609a5ee
Revises: 66b851b8fb2c
Create Date: 2026-02-05 12:26:57.411523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328b8609a5ee'
down_revision = '66b851b8fb2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__codes_investment_types',
    sa.Column('code', sa.Text(), nullable=False, comment='Originally reported short code.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Long human-readable description of the meaning of a code/label.'),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_core_rus7__codes_investment_types'))
    )
    op.create_table('core_rus7__scd_borrowers',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('state', sa.Text(), nullable=True, comment='Two letter US state abbreviation.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', name=op.f('pk_core_rus7__scd_borrowers'))
    )
    op.create_table('core_rus7__yearly_long_term_debt',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('debt_description', sa.Text(), nullable=True, comment='Description of debt or loan. On the original form, there are nine provided descriptions and a section to add other free-form descriptions.'),
    sa.Column('debt_ending_balance', sa.Float(), nullable=True, comment='The amount of principal still owned on the debt at the end of the report year.'),
    sa.Column('debt_interest', sa.Float(), nullable=True, comment='The interest expense on the debt for the report year.'),
    sa.Column('debt_principal', sa.Float(), nullable=True, comment='The principal paid on the debt during the report year.'),
    sa.Column('debt_total', sa.Float(), nullable=True, comment='The total amount of debt.')
    )
    op.create_table('core_rus7__yearly_patronage_capital',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('patronage_type', sa.Enum('total_received', 'distributions_special_retirements', 'total_distributions_retirements', 'received_lenders_of_electric_power', 'distributions_general_retirements', 'received_supplier_of_electric_power'), nullable=False, comment='Type of patronage capital distributed or received.'),
    sa.Column('patronage_report_year', sa.Float(), nullable=True, comment='Amount of patronage distributed or received within report year.'),
    sa.Column('patronage_cumulative', sa.Float(), nullable=True, comment='Amount of patronage distributed or received cumulatively. Received patronage capital is not reported cumulatively and thus will be null.'),
    sa.Column('is_total', sa.Boolean(), nullable=True, comment='Whether or not this record represents a total.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'patronage_type', name=op.f('pk_core_rus7__yearly_patronage_capital'))
    )
    op.create_table('core_rus7__yearly_statement_of_operations',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('opex_type', sa.Enum('operating_revenue', 'cost_of_electric_service', 'patronage_and_operating_margins', 'opex'), nullable=False, comment='High level section from the statement of operations table. Most of these types have subcomponents broken out in the ``statement_item_type`` column.'),
    sa.Column('opex_group', sa.Enum('interest_charged_to_construction', 'customer_service', 'power_production', 'purchased_power', 'other_deductions', 'total', 'operating_revenue', 'tax_other', 'customer_accounts', 'distribution_operation', 'total_minus', 'distribution_maintenance', 'interest_other', 'tax_property', 'transmission', 'interest_long_term_debt', 'regional_market', 'deprecation', 'sales', 'admin'), nullable=False, comment='Type of item from the statement of operations.'),
    sa.Column('opex_report_month', sa.Float(), nullable=True, comment='Amount of operational expense, cost or income during the report month.'),
    sa.Column('opex_ytd', sa.Float(), nullable=True, comment='The year-to-date amount of operational expense, cost or income.'),
    sa.Column('opex_ytd_budget', sa.Float(), nullable=True, comment='The year-to-date budget for amount of operational expense, cost or income.'),
    sa.Column('is_total', sa.Boolean(), nullable=True, comment='Whether or not this record represents a total.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'opex_type', 'opex_group', name=op.f('pk_core_rus7__yearly_statement_of_operations'))
    )
    op.create_table('core_rus7__yearly_investments',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('investment_description', sa.Text(), nullable=True, comment='Description of investment. This is a free-form text field and thus contains a wide variety of values.'),
    sa.Column('investment_type_code', sa.Integer(), nullable=True, comment='Investment type code.'),
    sa.Column('included_investments', sa.Float(), nullable=True, comment='Included investment.'),
    sa.Column('excluded_investments', sa.Float(), nullable=True, comment='Excluded investment.'),
    sa.Column('income_or_loss', sa.Float(), nullable=True, comment='Income or loss from investment.'),
    sa.Column('for_rural_development', sa.Boolean(), nullable=True, comment='Whether or not the investment is Rural Development.'),
    sa.ForeignKeyConstraint(['investment_type_code'], ['core_rus7__codes_investment_types.code'], name=op.f('fk_core_rus7__yearly_investments_investment_type_code_core_rus7__codes_investment_types'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_rus7__yearly_investments')
    op.drop_table('core_rus7__yearly_statement_of_operations')
    op.drop_table('core_rus7__yearly_patronage_capital')
    op.drop_table('core_rus7__yearly_long_term_debt')
    op.drop_table('core_rus7__scd_borrowers')
    op.drop_table('core_rus7__codes_investment_types')
    # ### end Alembic commands ###
