"""fix eia report_date primary keys

Revision ID: 34128b78508d
Revises: 08c64862ce26
Create Date: 2026-03-10 21:36:16.165085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34128b78508d'
down_revision = '08c64862ce26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "_core_eia923__yearly_byproduct_expenses_and_revenues", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk__core_eia923__yearly_byproduct_expenses_and_revenues"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk__core_eia923__yearly_byproduct_expenses_and_revenues"),
            ["plant_id_eia", "report_date"],
        )

    with op.batch_alter_table(
        "_core_eia923__yearly_byproduct_disposition", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk__core_eia923__yearly_byproduct_disposition"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk__core_eia923__yearly_byproduct_disposition"),
            ["plant_id_eia", "report_date", "byproduct_description"],
        )

    with op.batch_alter_table(
        "core_eia860__scd_emissions_control_equipment", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk_core_eia860__scd_emissions_control_equipment"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk_core_eia860__scd_emissions_control_equipment"),
            ["report_date", "plant_id_eia", "emission_control_id_pudl"],
        )

    with op.batch_alter_table(
        "out_eia860__yearly_emissions_control_equipment", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk_out_eia860__yearly_emissions_control_equipment"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk_out_eia860__yearly_emissions_control_equipment"),
            ["report_date", "plant_id_eia", "emission_control_id_pudl"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "out_eia860__yearly_emissions_control_equipment", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk_out_eia860__yearly_emissions_control_equipment"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk_out_eia860__yearly_emissions_control_equipment"),
            ["plant_id_eia", "emission_control_id_pudl"],
        )

    with op.batch_alter_table(
        "core_eia860__scd_emissions_control_equipment", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk_core_eia860__scd_emissions_control_equipment"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk_core_eia860__scd_emissions_control_equipment"),
            ["plant_id_eia", "emission_control_id_pudl"],
        )

    with op.batch_alter_table(
        "_core_eia923__yearly_byproduct_disposition", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk__core_eia923__yearly_byproduct_disposition"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk__core_eia923__yearly_byproduct_disposition"),
            ["plant_id_eia", "byproduct_description"],
        )

    with op.batch_alter_table(
        "_core_eia923__yearly_byproduct_expenses_and_revenues", schema=None
    ) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("pk__core_eia923__yearly_byproduct_expenses_and_revenues"),
            type_="primary",
        )
        batch_op.create_primary_key(
            batch_op.f("pk__core_eia923__yearly_byproduct_expenses_and_revenues"),
            ["plant_id_eia"],
        )
    # ### end Alembic commands ###
