"""Add PK to EIA-SEC crosswalk

Revision ID: 3973116789a3
Revises: b1e5f6ef3968
Create Date: 2025-03-28 19:57:24.586334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3973116789a3'
down_revision = 'b1e5f6ef3968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__assn_sec10k_filers_and_eia_utilities', schema=None) as batch_op:
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('utility_id_eia',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_primary_key('pk_core_sec10k__assn_sec10k_filers_and_eia_utilities', ['central_index_key', 'utility_id_eia'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__assn_sec10k_filers_and_eia_utilities', schema=None) as batch_op:
        batch_op.alter_column('utility_id_eia',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('central_index_key',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint('pk_core_sec10k__assn_sec10k_filers_and_eia_utilities', type_='primary')


    # ### end Alembic commands ###
