"""update db

Revision ID: 42cd9a3cd656
Revises: 4806a28e8863
Create Date: 2023-06-27 10:03:32.711858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cd9a3cd656'
down_revision = '4806a28e8863'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denorm_electric_plant_depreciation_changes_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dollar_value', sa.Float(), nullable=True, comment='Dollar value of reported income, expense, asset, or liability.'))
        batch_op.drop_column('utility_plant_value')

    with op.batch_alter_table('electric_plant_depreciation_changes_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dollar_value', sa.Float(), nullable=True, comment='Dollar value of reported income, expense, asset, or liability.'))
        batch_op.drop_column('utility_plant_value')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_plant_depreciation_changes_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_plant_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('dollar_value')

    with op.batch_alter_table('denorm_electric_plant_depreciation_changes_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utility_plant_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('dollar_value')

    # ### end Alembic commands ###
