"""add depreciation_type

Revision ID: 46858eb29d0a
Revises: 859ce5b091ca
Create Date: 2023-08-16 14:08:20.181687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46858eb29d0a'
down_revision = '859ce5b091ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_plant_depreciation_functional_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depreciation_type', sa.Text(), nullable=True, comment='Type of depreciation provision within FERC Account 108, including cost ofremoval, depreciation expenses, salvage, cost of retired plant, etc.'))
        batch_op.drop_column('ferc_account')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('electric_plant_depreciation_functional_ferc1', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ferc_account', sa.TEXT(), nullable=True))
        batch_op.drop_column('depreciation_type')

    # ### end Alembic commands ###
