"""add_core_eia176__yearly_company_characteristics

Revision ID: 48fade8aeee8
Revises: 4f252e9e2ce3
Create Date: 2026-04-21 08:27:53.098357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fade8aeee8'
down_revision = '4f252e9e2ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eia176__yearly_company_characteristics',
    sa.Column('report_year', sa.Integer(), nullable=False, comment='Four-digit year in which the data was reported.'),
    sa.Column('operator_id_eia', sa.Text(), nullable=False, comment='The unique EIA identifier for an operator in a given state. The last two letters of the ID indicate the state.'),
    sa.Column('operating_state', sa.Enum('AB', 'AK', 'AL', 'AR', 'AS', 'AZ', 'BC', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'GU', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MB', 'MD', 'ME', 'MI', 'MN', 'MO', 'MP', 'MS', 'MT', 'NB', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NL', 'NM', 'NS', 'NT', 'NU', 'NV', 'NY', 'OH', 'OK', 'ON', 'OR', 'PA', 'PE', 'PR', 'QC', 'RI', 'SC', 'SD', 'SK', 'TN', 'TX', 'UT', 'VA', 'VI', 'VT', 'WA', 'WI', 'WV', 'WY', 'YT'), nullable=True, comment='State that the operator is reporting for.'),
    sa.Column('is_distribution_company_cooperative', sa.Boolean(), nullable=True, comment='Whether the company is a cooperative distribution company.'),
    sa.Column('is_distribution_company_investor_owned', sa.Boolean(), nullable=True, comment='Whether the company is an investor-owned distribution company.'),
    sa.Column('is_distribution_company_municipally_owned', sa.Boolean(), nullable=True, comment='Whether the company is a municipally-owned distribution company.'),
    sa.Column('is_distribution_company_privately_owned', sa.Boolean(), nullable=True, comment='Whether the company is a privately-owned distribution company.'),
    sa.Column('is_gatherer', sa.Boolean(), nullable=True, comment='Whether the company operates as a natural gas gatherer.'),
    sa.Column('is_interstate_pipeline', sa.Boolean(), nullable=True, comment='Whether the company operates an interstate natural gas pipeline.'),
    sa.Column('is_intrastate_pipeline', sa.Boolean(), nullable=True, comment='Whether the company operates an intrastate natural gas pipeline.'),
    sa.Column('is_liquid_natural_gas_marine_terminal', sa.Boolean(), nullable=True, comment='Whether the company operates a liquefied natural gas marine terminal.'),
    sa.Column('is_liquid_natural_gas_peak_facility_operator', sa.Boolean(), nullable=True, comment='Whether the company operates a liquefied natural gas peak-shaving facility.'),
    sa.Column('is_producer', sa.Boolean(), nullable=True, comment='Whether the company operates as a natural gas producer.'),
    sa.Column('is_storage_operator', sa.Boolean(), nullable=True, comment='Whether the company operates natural gas storage facilities.'),
    sa.Column('is_synthetic_natural_gas_plant_operator', sa.Boolean(), nullable=True, comment='Whether the company operates a synthetic natural gas production plant.'),
    sa.Column('is_other_ownership', sa.Boolean(), nullable=True, comment='Whether the company reported an ownership type other than investor-owned, cooperative, municipal, or private.'),
    sa.Column('other_ownership_description', sa.Text(), nullable=True, comment="Free-text description of ownership type when 'other' ownership is indicated."),
    sa.Column('has_alternative_fuel_fleet', sa.Boolean(), nullable=True, comment='Whether the company operated a fleet of alternative-fuel vehicles during the report year.'),
    sa.Column('alternative_fleet_size', sa.Integer(), nullable=True, comment='Number of alternative-fuel vehicles in the company\'s fleet (EIA Form 176 Part 3, Line B).'),
    sa.Column('customer_choice_residential_eligible', sa.Integer(), nullable=True, comment='Number of residential customers eligible for customer choice programs (EIA Form 176 Part 3, Line C).'),
    sa.Column('customer_choice_residential_participating', sa.Integer(), nullable=True, comment='Number of residential customers participating in customer choice programs (EIA Form 176 Part 3, Line C).'),
    sa.Column('has_sales_or_acquisitions', sa.Boolean(), nullable=True, comment='Whether the company completed sales or acquisitions of natural gas distribution assets during the report year (EIA Form 176 Part 3, Line D).'),
    sa.Column('natural_gas_pump_price', sa.Float(), nullable=True, comment='Price of natural gas at public fueling stations operated by the company (EIA Form 176 Part 3, Line E). Reported 2014-2016 only.'),
    sa.Column('is_public_compressed_natural_gas_fueling_station', sa.Boolean(), nullable=True, comment='Whether the company operates a public compressed natural gas (CNG) fueling station.'),
    sa.Column('is_public_lng_fueling_station', sa.Boolean(), nullable=True, comment='Whether the company operates a public liquefied natural gas (LNG) fueling station.'),
    sa.PrimaryKeyConstraint('report_year', 'operator_id_eia', name=op.f('pk_core_eia176__yearly_company_characteristics'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_eia176__yearly_company_characteristics')
    # ### end Alembic commands ###
