"""Add my cool rus7 tables

Revision ID: 4aa20e0acd0a
Revises: e825be7a3ebe
Create Date: 2026-01-20 16:20:09.394549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa20e0acd0a'
down_revision = 'e825be7a3ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__yearly_balance_sheet_assets',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('asset_type', sa.Text(), nullable=False, comment='Type of asset being reported to the core_ferc1__yearly_balance_sheet_assets_sched110 table.'),
    sa.Column('balance', sa.Text(), nullable=True, comment='Indication of whether a column is a credit or debit, as reported in the XBRL taxonomy.'),
    sa.Column('is_total', sa.Boolean(), nullable=True, comment='Whether or not this record represents a total.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'asset_type', name=op.f('pk_core_rus7__yearly_balance_sheet_assets'))
    )
    op.create_table('core_rus7__yearly_meeting_and_board',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('last_annual_meeting_date', sa.Text(), nullable=True, comment='The date of the last annual meeting.'),
    sa.Column('members_num', sa.Integer(), nullable=True, comment='The total number of members.'),
    sa.Column('members_present_at_meeting_num', sa.Integer(), nullable=True, comment='The number of members present at the last annual meeting.'),
    sa.Column('was_quorum_present', sa.Boolean(), nullable=True, comment='Whether or not quorum was met.'),
    sa.Column('members_voting_by_proxy_or_mail_num', sa.Integer(), nullable=True, comment='The number of members voting by mail or by proxy.'),
    sa.Column('board_members_num', sa.Integer(), nullable=True, comment='The total number of board members.'),
    sa.Column('fees_and_expenses_for_board_members', sa.Integer(), nullable=True, comment='The total amount of fees and expenses for board members.'),
    sa.Column('does_manager_have_written_contract', sa.Boolean(), nullable=True, comment="Whether or not the RUS borrower's manager has a written contract."),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', name=op.f('pk_core_rus7__yearly_meeting_and_board'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_rus7__yearly_meeting_and_board')
    op.drop_table('core_rus7__yearly_balance_sheet_assets')
    # ### end Alembic commands ###
