"""merge peak_demand_hour to date

Revision ID: 5103951c5174
Revises: d5a8f9e711be
Create Date: 2026-03-19 16:30:36.099007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5103951c5174'
down_revision = 'd5a8f9e711be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rus12__monthly_demand_and_energy_at_power_sources', schema=None) as batch_op:
        batch_op.drop_column('peak_demand_hour')

    with op.batch_alter_table('out_rus12__monthly_demand_and_energy_at_power_sources', schema=None) as batch_op:
        batch_op.drop_column('peak_demand_hour')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_rus12__monthly_demand_and_energy_at_power_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peak_demand_hour', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('core_rus12__monthly_demand_and_energy_at_power_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peak_demand_hour', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
