"""update

Revision ID: 6c84ecc06d2e
Revises: de2072d3669f
Create Date: 2026-01-09 13:10:24.837289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c84ecc06d2e'
down_revision = 'de2072d3669f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
