"""Add core_eia176__yearly_gas_exports

Revision ID: 6e7e5e016fd3
Revises: dec47cde2e19
Create Date: 2026-05-18 12:06:22.418085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7e5e016fd3'
down_revision = 'dec47cde2e19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eia176__yearly_gas_exports',
    sa.Column('operator_id_eia', sa.Text(), nullable=True, comment='The unique EIA identifier for an operator in a given state. The last two letters of the ID indicate the state.'),
    sa.Column('report_year', sa.Integer(), nullable=True, comment='Four-digit year in which the data was reported.'),
    sa.Column('operating_state', sa.Text(), nullable=True, comment='State that the distribution utility is reporting for. Prior to 2004, this may be a list of states.'),
    sa.Column('destination_code', sa.Text(), nullable=True, comment='State, territory, country, or other reporting code associated with the out-of-state gas delivery destination.'),
    sa.Column('destination_type', sa.Enum('country_or_other', 'subdivision'), nullable=True, comment='Type of delivery destination represented by the destination code.'),
    sa.Column('recipient_name', sa.Text(), nullable=True, comment='Reported recipient or counterparty for the out-of-state gas delivery.'),
    sa.Column('mode_of_transportation', sa.Enum('pipeline', 'truck', 'vessel'), nullable=True, comment='Means by which natural gas was transported.'),
    sa.Column('volume_mcf', sa.Float(), nullable=True, comment='Volume of natural gas delivered out of the report state. Reference conditions for measurement are 14.73 psia and 60° Fahrenheit.')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_eia176__yearly_gas_exports')
    # ### end Alembic commands ###
