"""eia191 monthly gas storage

Revision ID: 6f78472056c4
Revises: 4c3808642f32
Create Date: 2026-03-24 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f78472056c4"
down_revision = "4c3808642f32"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "core_eia191__monthly_gas_storage",
        sa.Column(
            "storage_field_id_eia191",
            sa.Text(),
            nullable=False,
            comment=(
                "EIA-assigned identifier for an underground natural gas storage reservoir, "
                "as reported on Form 191. Uniquely identifies a reservoir across all "
                "reporting periods."
            ),
        ),
        sa.Column(
            "report_date",
            sa.Date(),
            nullable=False,
            comment="Date reported.",
        ),
        sa.Column(
            "state",
            sa.Text(),
            nullable=True,
            comment="Two letter US state abbreviation.",
        ),
        sa.Column(
            "gas_field_code",
            sa.Text(),
            nullable=True,
            comment="EIA-assigned code identifying the natural gas storage field, as reported on Form 191.",
        ),
        sa.Column(
            "reservoir_code",
            sa.Text(),
            nullable=True,
            comment=(
                "EIA-assigned code identifying the individual storage reservoir within "
                "a natural gas storage field, as reported on Form 191."
            ),
        ),
        sa.Column(
            "company_name",
            sa.Text(),
            nullable=True,
            comment="Name of the reporting company.",
        ),
        sa.Column(
            "field_name",
            sa.Text(),
            nullable=True,
            comment=(
                "Name of the natural gas storage field, as reported by the operator to "
                "EIA on Form 191."
            ),
        ),
        sa.Column(
            "reservoir_name",
            sa.Text(),
            nullable=True,
            comment=(
                "Name of the individual underground natural gas storage reservoir, "
                "as reported by the operator to EIA on Form 191."
            ),
        ),
        sa.Column(
            "field_type",
            sa.Enum("aquifer", "depleted field", "salt dome"),
            nullable=True,
            comment=(
                "Type of underground natural gas storage facility, as reported to EIA on "
                "Form 191. One of: depleted field (a reservoir previously used for natural "
                "gas production), aquifer (a porous rock structure used to store gas), or "
                "salt dome (a cavern created within a salt formation)."
            ),
        ),
        sa.Column(
            "county_name",
            sa.Text(),
            nullable=True,
            comment=(
                "Name of the county in which the storage reservoir is located, as reported "
                "to EIA on Form 191."
            ),
        ),
        sa.Column(
            "status",
            sa.Enum("active", "inactive"),
            nullable=True,
            comment=(
                "Operational status of the underground natural gas storage reservoir, "
                "as reported to EIA on Form 191."
            ),
        ),
        sa.Column(
            "base_gas_mcf",
            sa.Float(),
            nullable=True,
            comment=(
                "Volume of base gas (cushion gas) in the underground storage reservoir, "
                "as reported by the operator to EIA on Form 191. Base gas is the volume "
                "of gas intended as permanent inventory in a reservoir to maintain "
                "adequate pressure and deliverability rates."
            ),
        ),
        sa.Column(
            "working_gas_capacity_mcf",
            sa.Float(),
            nullable=True,
            comment=(
                "Volume of working gas (the portion of stored gas available for withdrawal) "
                "in the underground storage reservoir, as reported by the operator to EIA "
                "on Form 191."
            ),
        ),
        sa.Column(
            "total_field_capacity_mcf",
            sa.Float(),
            nullable=True,
            comment=(
                "Total design capacity of the underground natural gas storage field "
                "(base gas plus working gas), as reported by the operator to EIA on "
                "Form 191. Note: this value is not reliably equal to the sum of "
                "working_gas_capacity_mcf and base_gas_mcf; approximately 23% of "
                "records differ, reflecting loose EIA definitions and operator "
                "self-reporting practices."
            ),
        ),
        sa.Column(
            "maximum_daily_delivery_mcf",
            sa.Float(),
            nullable=True,
            comment=(
                "Maximum daily quantity of gas that can be withdrawn from the underground "
                "storage reservoir under normal operating conditions, as reported by the "
                "operator to EIA on Form 191."
            ),
        ),
        sa.Column(
            "region",
            sa.Enum("alaska", "east region", "midwest region", "mountain region", "pacific region", "south central region"),
            nullable=True,
            comment=(
                "EIA storage region in which the underground natural gas storage field "
                "is located, as reported on Form 191."
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("core_eia191__monthly_gas_storage")
    # ### end Alembic commands ###
