"""change 923 column name combined_heat_power to associated_combined_heat_power to match 860

Revision ID: 855f2d3746a9
Revises: 41120381bfda
Create Date: 2024-03-28 14:13:14.880435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855f2d3746a9'
down_revision = '41120381bfda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_ferc1__yearly_balance_sheet_assets_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_balance_sheet_liabilities_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_cash_flows_sched120', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_by_function_sched219', schema=None) as batch_op:
        batch_op.alter_column('depreciation_type',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_changes_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_summary_sched336', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_energy_dispositions_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_energy_sources_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_income_statements_sched114', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_operating_expenses_sched320', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_operating_revenues_sched300', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_plant_in_service_sched204', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_retained_earnings_sched118', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_utility_plant_summary_sched200', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_balance_sheet_assets_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_balance_sheet_liabilities_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_cash_flows_sched120', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_depreciation_by_function_sched219', schema=None) as batch_op:
        batch_op.alter_column('depreciation_type',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_depreciation_changes_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_energy_dispositions_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_energy_sources_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_income_statements_sched114', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_operating_expenses_sched320', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_operating_revenues_sched300', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_plant_in_service_sched204', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_retained_earnings_sched118', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_utility_plant_summary_sched200', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_ferc1__yearly_utility_plant_summary_sched200', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_retained_earnings_sched118', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_plant_in_service_sched204', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_operating_revenues_sched300', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_operating_expenses_sched320', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_income_statements_sched114', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_energy_sources_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_energy_dispositions_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_depreciation_changes_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_depreciation_by_function_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('depreciation_type',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_cash_flows_sched120', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_balance_sheet_liabilities_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_balance_sheet_assets_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_utility_plant_summary_sched200', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_retained_earnings_sched118', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_plant_in_service_sched204', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_operating_revenues_sched300', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_operating_expenses_sched320', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_income_statements_sched114', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_energy_sources_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_energy_dispositions_sched401', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_summary_sched336', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_changes_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_depreciation_by_function_sched219', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('depreciation_type',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_cash_flows_sched120', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_balance_sheet_liabilities_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    with op.batch_alter_table('core_ferc1__yearly_balance_sheet_assets_sched110', schema=None) as batch_op:
        batch_op.alter_column('row_type_xbrl',
               existing_type=sa.Enum('calculated_value', 'reported_value', 'correction', 'subdimension_correction'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
