"""Standardize steam_load units

Revision ID: 86650ef68d57
Revises: e825be7a3ebe
Create Date: 2026-01-01 21:56:32.280494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86650ef68d57'
down_revision = 'e825be7a3ebe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
