"""add cooling equipment

Revision ID: 898f7d0900ec
Revises: 172d3ee0d2f2
Create Date: 2024-03-12 12:13:32.448237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898f7d0900ec'
down_revision = '172d3ee0d2f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_core_eia860__cooling_equipment',
    sa.Column('plant_id_eia', sa.Integer(), nullable=False, comment='The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.'),
    sa.Column('cooling_id_eia', sa.Text(), nullable=False, comment="EIA Identification code for cooling system (if multiple cooling systems are not distinguished by separate IDs, the word 'PLANT' is listed to encompass the cooling system for the entire plant)"),
    sa.Column('utility_id_eia', sa.Integer(), nullable=False, comment='The EIA Utility Identification number.'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('chlorine_equipment_cost', sa.Float(), nullable=True, comment='Actual installed cost for the existing chlorine discharge control system or the anticipated cost to bring the chlorine discharge control system into commercial operation'),
    sa.Column('chlorine_equipment_operating_date', sa.Date(), nullable=True, comment='Actual or projected in-service date for chlorine discharge control structures and equipment'),
    sa.Column('cooling_equipment_total_cost', sa.Float(), nullable=True, comment='Actual installed cost for the existing system or the anticipated cost to bring the total system into commercial operation'),
    sa.Column('cooling_status_code', sa.Text(), nullable=True, comment='Operating status of cooling system'),
    sa.Column('cooling_system_operating_date', sa.Date(), nullable=True, comment='The actual or projected in-service datetime of this cooling system'),
    sa.Column('cooling_type_1', sa.Text(), nullable=True, comment='Type of cooling system'),
    sa.Column('cooling_type_2', sa.Text(), nullable=True, comment='Type of cooling system'),
    sa.Column('cooling_type_3', sa.Text(), nullable=True, comment='Type of cooling system'),
    sa.Column('cooling_type_4', sa.Text(), nullable=True, comment='Type of cooling system'),
    sa.Column('cooling_water_discharge', sa.Text(), nullable=True, comment='Name of river, lake, or water source that cooling water is discharged into'),
    sa.Column('cooling_water_source', sa.Text(), nullable=True, comment='Name of river, lake, or water source that provides cooling water'),
    sa.Column('county', sa.Text(), nullable=True, comment='County name.'),
    sa.Column('intake_distance_shore_feet', sa.Float(), nullable=True, comment='Maximum distance from shore to intake'),
    sa.Column('intake_distance_surface_feet', sa.Float(), nullable=True, comment='Average distance below water surface to intake'),
    sa.Column('intake_rate_100pct_gallons_per_minute', sa.Float(), nullable=True, comment='Design cooling water flow rate at 100 percent load at in-take'),
    sa.Column('outlet_distance_shore_feet', sa.Float(), nullable=True, comment='Maximum distance from shore to outlet'),
    sa.Column('outlet_distance_surface_feet', sa.Float(), nullable=True, comment='Average distance below water surface to outlet'),
    sa.Column('percent_dry_cooling', sa.Float(), nullable=True, comment='Percent of cooling load served by dry cooling components'),
    sa.Column('plant_name_eia', sa.Text(), nullable=True, comment='Plant name.'),
    sa.Column('plant_summer_capacity_mw', sa.Float(), nullable=True, comment='The plant summer capacity associated with the operating generators at the plant'),
    sa.Column('pond_cost', sa.Float(), nullable=True, comment='Actual installed cost for the existing cooling ponds or the anticipated cost to bring the cooling ponds into commercial operation'),
    sa.Column('pond_operating_date', sa.Date(), nullable=True, comment='Cooling ponds actual or projected in-service date'),
    sa.Column('pond_surface_area_acres', sa.Float(), nullable=True, comment='Total surface area of cooling pond'),
    sa.Column('pond_volume_acre_feet', sa.Float(), nullable=True, comment='Total volume of water in cooling pond'),
    sa.Column('power_requirement_mw', sa.Float(), nullable=True, comment='Maximum power requirement for cooling towers at 100 percent load'),
    sa.Column('state', sa.Text(), nullable=True, comment='Two letter US state abbreviation.'),
    sa.Column('steam_plant_type_code', sa.Integer(), nullable=True, comment='Code that describes types of steam plants from EIA 860. See steam_plant_types_eia table for more details.'),
    sa.Column('tower_cost', sa.Float(), nullable=True, comment='Actual installed cost for the existing cooling towers or the anticipated cost to bring the cooling towers into commercial operation'),
    sa.Column('tower_operating_date', sa.Date(), nullable=True, comment='Cooling towers actual or projected in-service date'),
    sa.Column('tower_type_1', sa.Text(), nullable=True, comment='Types of cooling towers at this plant'),
    sa.Column('tower_type_2', sa.Text(), nullable=True, comment='Types of cooling towers at this plant'),
    sa.Column('tower_type_3', sa.Text(), nullable=True, comment='Types of cooling towers at this plant'),
    sa.Column('tower_type_4', sa.Text(), nullable=True, comment='Types of cooling towers at this plant'),
    sa.Column('tower_water_rate_100pct_gallons_per_minute', sa.Float(), nullable=True, comment='Maximum design rate of water flow at 100 percent load for the cooling towers'),
    sa.Column('utility_name_eia', sa.Text(), nullable=True, comment='The name of the utility.'),
    sa.Column('water_source_code', sa.Text(), nullable=True, comment='Type of cooling water source'),
    sa.Column('water_source', sa.Text(), nullable=True, comment='Name of water source associated with the plant.'),
    sa.Column('water_type_code', sa.Text(), nullable=True, comment='Type of cooling water'),
    sa.ForeignKeyConstraint(['plant_id_eia', 'report_date'], ['core_eia860__scd_plants.plant_id_eia', 'core_eia860__scd_plants.report_date'], name=op.f('fk__core_eia860__cooling_equipment_plant_id_eia_core_eia860__scd_plants')),
    sa.ForeignKeyConstraint(['steam_plant_type_code'], ['core_eia__codes_steam_plant_types.code'], name=op.f('fk__core_eia860__cooling_equipment_steam_plant_type_code_core_eia__codes_steam_plant_types')),
    sa.ForeignKeyConstraint(['tower_type_1'], ['core_eia__codes_cooling_tower_types.code'], name=op.f('fk__core_eia860__cooling_equipment_tower_type_1_core_eia__codes_cooling_tower_types')),
    sa.ForeignKeyConstraint(['tower_type_2'], ['core_eia__codes_cooling_tower_types.code'], name=op.f('fk__core_eia860__cooling_equipment_tower_type_2_core_eia__codes_cooling_tower_types')),
    sa.ForeignKeyConstraint(['tower_type_3'], ['core_eia__codes_cooling_tower_types.code'], name=op.f('fk__core_eia860__cooling_equipment_tower_type_3_core_eia__codes_cooling_tower_types')),
    sa.ForeignKeyConstraint(['tower_type_4'], ['core_eia__codes_cooling_tower_types.code'], name=op.f('fk__core_eia860__cooling_equipment_tower_type_4_core_eia__codes_cooling_tower_types')),
    sa.ForeignKeyConstraint(['utility_id_eia', 'report_date'], ['core_eia860__scd_utilities.utility_id_eia', 'core_eia860__scd_utilities.report_date'], name=op.f('fk__core_eia860__cooling_equipment_utility_id_eia_core_eia860__scd_utilities')),
    sa.ForeignKeyConstraint(['water_type_code'], ['core_eia__codes_cooling_water_types.code'], name=op.f('fk__core_eia860__cooling_equipment_water_type_code_core_eia__codes_cooling_water_types')),
    sa.PrimaryKeyConstraint('plant_id_eia', 'utility_id_eia', 'cooling_id_eia', 'report_date', name=op.f('pk__core_eia860__cooling_equipment'))
    )
    op.create_table('_core_eia923__cooling_system_information',
    sa.Column('plant_id_eia', sa.Integer(), nullable=False, comment='The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('cooling_id_eia', sa.Text(), nullable=False, comment="EIA Identification code for cooling system (if multiple cooling systems are not distinguished by separate IDs, the word 'PLANT' is listed to encompass the cooling system for the entire plant)"),
    sa.Column('annual_average_consumption_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Annual average consumption rate of cooling water'),
    sa.Column('annual_average_discharge_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Annual average discharge rate of cooling water'),
    sa.Column('annual_average_withdrawal_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Annual average withdrawal rate of cooling water'),
    sa.Column('annual_maximum_intake_summer_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at intake during the summer'),
    sa.Column('annual_maximum_intake_winter_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at intake in winter'),
    sa.Column('annual_maximum_outlet_summer_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at outlet in summer'),
    sa.Column('annual_maximum_outlet_winter_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at outlet in winter'),
    sa.Column('annual_total_chlorine_lbs', sa.Float(), nullable=True, comment='Amount of elemental chlorine added to cooling water annually. May be just the amount of chlorine-containing compound if schedule 9 is filled out.'),
    sa.Column('monthly_total_cooling_hours_in_service', sa.Integer(), nullable=True, comment='Total hours the system operated during the month'),
    sa.Column('cooling_status_code', sa.Text(), nullable=True, comment='Operating status of cooling system'),
    sa.Column('cooling_type', sa.Text(), nullable=True, comment='Type of cooling system'),
    sa.Column('flow_rate_method', sa.Text(), nullable=True, comment='Calculation method for flow rates (actual or method of estimation)'),
    sa.Column('monthly_average_consumption_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Monthly average consumption rate of cooling water'),
    sa.Column('monthly_average_discharge_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Monthly average discharge rate of cooling water - available 2010+'),
    sa.Column('monthly_average_discharge_temperature_fahrenheit', sa.Float(), nullable=True, comment='Average cooling water temperature at discharge point'),
    sa.Column('monthly_average_diversion_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Monthly average diversion rate of cooling water'),
    sa.Column('monthly_average_intake_temperature_fahrenheit', sa.Float(), nullable=True, comment='Average cooling water temperature at intake point'),
    sa.Column('monthly_average_withdrawal_rate_gallons_per_minute', sa.Float(), nullable=True, comment='Monthly average withdrawal rate of cooling water'),
    sa.Column('monthly_total_chlorine_lbs', sa.Float(), nullable=True, comment='Amount of elemental chlorine added to cooling water monthly. May be just the amount of chlorine-containing compound if schedule 9 is filled out.'),
    sa.Column('monthly_maximum_discharge_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at discharge'),
    sa.Column('monthly_maximum_intake_temperature_fahrenheit', sa.Float(), nullable=True, comment='Maximum cooling water temperature at intake'),
    sa.Column('monthly_total_consumption_volume_gallons', sa.Float(), nullable=True, comment='Monthly volume of water consumed at consumption point (accurate to 0.1 million gal)'),
    sa.Column('monthly_total_discharge_volume_gallons', sa.Float(), nullable=True, comment='Monthly volume of water discharged at discharge point (accurate to 0.1 million gal)'),
    sa.Column('monthly_total_diversion_volume_gallons', sa.Float(), nullable=True, comment='Monthly volume of water diverted at diversion point (accurate to 0.1 million gal)'),
    sa.Column('monthly_total_withdrawal_volume_gallons', sa.Float(), nullable=True, comment='Monthly volume of water withdrawn at withdrawal point (accurate to 0.1 million gal)'),
    sa.Column('temperature_method', sa.Text(), nullable=True, comment='Method for measurement of temperatures'),
    sa.ForeignKeyConstraint(['plant_id_eia', 'report_date'], ['core_eia860__scd_plants.plant_id_eia', 'core_eia860__scd_plants.report_date'], name=op.f('fk__core_eia923__cooling_system_information_plant_id_eia_core_eia860__scd_plants')),
    sa.PrimaryKeyConstraint('plant_id_eia', 'report_date', 'cooling_id_eia', name=op.f('pk__core_eia923__cooling_system_information'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_core_eia923__cooling_system_information')
    op.drop_table('_core_eia860__cooling_equipment')
    # ### end Alembic commands ###
