"""add even more cool rus7 tables

Revision ID: 8fd7539bd87d
Revises: 9c66ca6fcafa
Create Date: 2026-01-27 13:36:13.389942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd7539bd87d'
down_revision = '9c66ca6fcafa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__yearly_investments',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('investment_description', sa.Text(), nullable=True, comment='Description of investment. This is a free-form text field and thus contains a wide variety of values.'),
    sa.Column('investment_type_code', sa.Integer(), nullable=True, comment='Investment type code.'),
    sa.Column('included_investments', sa.Float(), nullable=True, comment='Included investment.'),
    sa.Column('excluded_investments', sa.Float(), nullable=True, comment='Excluded investment.'),
    sa.Column('income_or_loss', sa.Float(), nullable=True, comment='Income or loss from investment.'),
    sa.Column('is_rural_development_investment', sa.Boolean(), nullable=True, comment='Whether or not the investment is Rural Development.')
    )
    op.create_table('core_rus7__yearly_long_term_debt',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('debt_description', sa.Text(), nullable=True, comment='Description of debt or loan. On the original form, there are nine provided descriptions and a section to add other free-form descriptions.'),
    sa.Column('balance_end_of_report_year', sa.Float(), nullable=True, comment='Loan or debt balance at end of report year.'),
    sa.Column('loan_interest', sa.Float(), nullable=True, comment='Loan or debt interest billed during this report year.'),
    sa.Column('loan_principal', sa.Float(), nullable=True, comment='Loan or debt principal billed during this report year.'),
    sa.Column('loan_total', sa.Float(), nullable=True, comment='Loan or debt total billed during this report year.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', name=op.f('pk_core_rus7__yearly_long_term_debt'))
    )
    op.create_table('core_rus7__yearly_patronage_capital',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('patronage_type', sa.Enum('total_received', 'distributions_general_retirements', 'distributions_special_retirements', 'total_distributions_retirements', 'received_supplier_of_electric_power', 'received_lenders_of_electric_power'), nullable=False, comment='Type of patronage capital distributed or received.'),
    sa.Column('patronage_report_year', sa.Float(), nullable=True, comment='Amount of patronage distributed or received within report year.'),
    sa.Column('patronage_cumulative', sa.Float(), nullable=True, comment='Amount of patronage distributed or received cumulatively. Received patronage capital is notreported cumulatively and thus will be null.'),
    sa.Column('is_total', sa.Boolean(), nullable=True, comment='Whether or not this record represents a total.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'patronage_type', name=op.f('pk_core_rus7__yearly_patronage_capital'))
    )
    op.create_table('core_rus7__yearly_statement_of_operations',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('statement_type', sa.Enum('patronage_and_operating_margins', 'electric_service_expense', 'operating_revenue', 'opex'), nullable=True, comment='High level section from the statement of operations table. Most of these types have subcomponents broken out in the ``statement_item_type`` column.'),
    sa.Column('statement_item_type', sa.Enum('deprecation', 'regional_market', 'operating_revenue', 'total_minus', 'interest_long_term_debt', 'admin', 'purchased_power', 'distribution_maintenance', 'distribution_operation', 'power_production', 'customer_service', 'tax_other', 'customer_accounts', 'other_deductions', 'interest_other', 'tax_property', 'transmission', 'sales', 'interest_charged_to_construction', 'total'), nullable=False, comment='Type of item from the statement of operations.'),
    sa.Column('observation_period', sa.Enum('cumulative', 'avg', 'december', 'ytd_budget', 'ytd', 'new_in_report_year', 'report_year', 'report_month'), nullable=False, comment="The date range that any given record pertains to. Ex: 'december' implies that this record covers the month of December only, while 'avg' implies this record pertains to the average of the reporting period."),
    sa.Column('amount', sa.Float(), nullable=True, comment='Reported amount of dollars. This could be a balance or a change in value.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'statement_item_type', 'observation_period', name=op.f('pk_core_rus7__yearly_statement_of_operations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_rus7__yearly_statement_of_operations')
    op.drop_table('core_rus7__yearly_patronage_capital')
    op.drop_table('core_rus7__yearly_long_term_debt')
    op.drop_table('core_rus7__yearly_investments')
    # ### end Alembic commands ###
