"""Add epacamd_eia back to datasources enum

Revision ID: 955e745a9fbd
Revises: 997d2c7bc7de
Create Date: 2024-01-25 14:15:03.711635

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '955e745a9fbd'
down_revision = '997d2c7bc7de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_pudl__codes_datasources', schema=None) as batch_op:
        batch_op.alter_column('datasource',
               existing_type=sa.VARCHAR(length=26),
               type_=sa.Enum('censusdp1tract', 'eia176', 'eia860', 'eia860m', 'eia861', 'eia923', 'eia_bulk_elec', 'eiawater', 'epacems', 'epacamd_eia', 'ferc1', 'ferc2', 'ferc6', 'ferc60', 'ferc714', 'ferceqr', 'mshamines', 'phmsagas', 'pudl'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_pudl__codes_datasources', schema=None) as batch_op:
        batch_op.alter_column('datasource',
               existing_type=sa.Enum('censusdp1tract', 'eia176', 'eia860', 'eia860m', 'eia861', 'eia923', 'eia_bulk_elec', 'eiawater', 'epacems', 'epacamd_eia', 'ferc1', 'ferc2', 'ferc6', 'ferc60', 'ferc714', 'ferceqr', 'mshamines', 'phmsagas', 'pudl'),
               type_=sa.VARCHAR(length=26),
               existing_nullable=False)

    # ### end Alembic commands ###
