"""Update row_type_xbrl enum

Revision ID: 9680af0e1432
Revises: 57ccd33ab8c2
Create Date: 2023-06-02 11:13:30.018363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9680af0e1432'
down_revision = '57ccd33ab8c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
