"""add new storage and solar columns from 2023 860 ER

Revision ID: 9891f104b622
Revises: da38a41d7f99
Create Date: 2024-06-18 14:19:56.264570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9891f104b622'
down_revision = 'da38a41d7f99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eia860__scd_generators_energy_storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ac_coupled', sa.Boolean(), nullable=True, comment='Indicates if this energy storage device is AC-coupled (means the energy storage device and the PV system are not installed on the same side of an inverter).'))
        batch_op.add_column(sa.Column('is_dc_coupled', sa.Boolean(), nullable=True, comment='Indicates if this energy storage device is DC-coupled (means the energy storage device and the PV system are on the same side of an inverter and the battery can still charge from the grid).'))
        batch_op.add_column(sa.Column('id_dc_coupled_tightly', sa.Boolean(), nullable=True, comment='Indicates if this energy storage device is tightly DC-coupled (means the energy storage device and the PV system are on the same side of an inverter and the battery can still charge from the grid).'))
        batch_op.add_column(sa.Column('is_independent', sa.Boolean(), nullable=True, comment='Indicates if this energy storage device is Independent (not coupled with another generators)'))
        batch_op.add_column(sa.Column('is_transmission_and_distribution_asset_support', sa.Boolean(), nullable=True, comment='Indicate if the energy storage system intended to support a specific substation, transmission or distribution asset.'))
        batch_op.add_column(sa.Column('is_direct_support', sa.Boolean(), nullable=True, comment='Indicates if this energy storage device is intended for dedicated generator firming or storing excess generation of other units'))
        batch_op.add_column(sa.Column('plant_id_eia_direct_support_1', sa.Float(), nullable=True, comment='Indicate the primary EIA Plant ID of the unit whose generation this energy storage device is intended to firm or store.'))
        batch_op.add_column(sa.Column('generator_id_direct_support_1', sa.Text(), nullable=True, comment='Indicate the primary EIA Generator ID of the unit whose generation this energy storage device is intended to firm or store.'))
        batch_op.add_column(sa.Column('plant_id_eia_direct_support_2', sa.Float(), nullable=True, comment='Indicate the second EIA Plant ID of the unit whose generation this energy storage device is intended to firm or store.'))
        batch_op.add_column(sa.Column('generator_id_direct_support_2', sa.Text(), nullable=True, comment='Indicate the second EIA Generator ID of the unit whose generation this energy storage device is intended to firm or store.'))
        batch_op.add_column(sa.Column('plant_id_eia_direct_support_3', sa.Float(), nullable=True, comment='Indicate the third EIA Plant ID of the unit whose generation this energy storage device is intended to firm or store.'))
        batch_op.add_column(sa.Column('generator_id_direct_support_3', sa.Text(), nullable=True, comment='Indicate the third EIA Generator ID of the unit whose generation this energy storage device is intended to firm or store.'))

    with op.batch_alter_table('core_eia860__scd_generators_solar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uses_bifacial', sa.Boolean(), nullable=True, comment='Indicates whether bifacial solar panels are used at this solar generating unit.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eia860__scd_generators_solar', schema=None) as batch_op:
        batch_op.drop_column('uses_bifacial')

    with op.batch_alter_table('core_eia860__scd_generators_energy_storage', schema=None) as batch_op:
        batch_op.drop_column('generator_id_direct_support_3')
        batch_op.drop_column('plant_id_eia_direct_support_3')
        batch_op.drop_column('generator_id_direct_support_2')
        batch_op.drop_column('plant_id_eia_direct_support_2')
        batch_op.drop_column('generator_id_direct_support_1')
        batch_op.drop_column('plant_id_eia_direct_support_1')
        batch_op.drop_column('is_direct_support')
        batch_op.drop_column('is_transmission_and_distribution_asset_support')
        batch_op.drop_column('is_independent')
        batch_op.drop_column('id_dc_coupled_tightly')
        batch_op.drop_column('is_dc_coupled')
        batch_op.drop_column('is_ac_coupled')

    # ### end Alembic commands ###
