"""Exclude FRC table FKs

Revision ID: 9e1194f1487c
Revises: ae144ab77d85
Create Date: 2026-03-03 12:45:55.738533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1194f1487c'
down_revision = 'ae144ab77d85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eia923__fuel_receipts_costs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_core_eia923__fuel_receipts_costs_plant_id_eia_core_eia860__scd_plants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_core_eia923__fuel_receipts_costs_plant_id_eia_core_eia__entity_plants'), 'core_eia__entity_plants', ['plant_id_eia'], ['plant_id_eia'])

    with op.batch_alter_table('out_eia923__fuel_receipts_costs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_out_eia923__fuel_receipts_costs_plant_id_eia_core_eia860__scd_plants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_out_eia923__fuel_receipts_costs_plant_id_eia_core_eia__entity_plants'), 'core_eia__entity_plants', ['plant_id_eia'], ['plant_id_eia'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_eia923__fuel_receipts_costs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_out_eia923__fuel_receipts_costs_plant_id_eia_core_eia__entity_plants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_out_eia923__fuel_receipts_costs_plant_id_eia_core_eia860__scd_plants'), 'core_eia860__scd_plants', ['plant_id_eia', 'report_date'], ['plant_id_eia', 'report_date'])

    with op.batch_alter_table('core_eia923__fuel_receipts_costs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_core_eia923__fuel_receipts_costs_plant_id_eia_core_eia__entity_plants'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_core_eia923__fuel_receipts_costs_plant_id_eia_core_eia860__scd_plants'), 'core_eia860__scd_plants', ['plant_id_eia', 'report_date'], ['plant_id_eia', 'report_date'])

    # ### end Alembic commands ###
