"""Add my cool table

Revision ID: a56fa0739cd7
Revises: 450d100cd30b
Create Date: 2024-11-16 20:46:01.862062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56fa0739cd7'
down_revision = '450d100cd30b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
