"""Update something?

Revision ID: a61c683e874c
Revises: 946864e58a8e
Create Date: 2024-02-08 11:58:44.313068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61c683e874c'
down_revision = '946864e58a8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eia860m__changelog_generators',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('valid_till_date', sa.Date(), nullable=True, comment='The record in the changelog is valid until this date. The record is valid from the report_date up until but not including the valid_till_date.'),
    sa.Column('plant_id_eia', sa.Integer(), nullable=False, comment='The unique six-digit facility identification number, also called an ORISPL, assigned by the Energy Information Administration.'),
    sa.Column('plant_name_eia', sa.Text(), nullable=True, comment='Plant name.'),
    sa.Column('utility_id_eia', sa.Integer(), nullable=True, comment='The EIA Utility Identification number.'),
    sa.Column('utility_name_eia', sa.Text(), nullable=True, comment='The name of the utility.'),
    sa.Column('generator_id', sa.Text(), nullable=False, comment='Generator ID is usually numeric, but sometimes includes letters. Make sure you treat it as a string!'),
    sa.Column('capacity_mw', sa.Float(), nullable=True, comment='Total installed (nameplate) capacity, in megawatts.'),
    sa.Column('county', sa.Text(), nullable=True, comment='County name.'),
    sa.Column('current_planned_generator_operating_date', sa.Date(), nullable=True, comment='The most recently updated effective date on which the generator is scheduled to start operation'),
    sa.Column('data_maturity', sa.Text(), nullable=True, comment='Level of maturity of the data record. Some data sources report less-than-final data. PUDL sometimes includes this data, but use at your own risk.'),
    sa.Column('energy_source_code_1', sa.Text(), nullable=True, comment='The code representing the most predominant type of energy that fuels the generator.'),
    sa.Column('energy_storage_capacity_mwh', sa.Float(), nullable=True, comment='Energy storage capacity in MWh (e.g. for batteries).'),
    sa.Column('fuel_type_code_pudl', sa.Enum('coal', 'gas', 'hydro', 'nuclear', 'oil', 'other', 'solar', 'waste', 'wind'), nullable=True, comment='Simplified fuel type code used in PUDL'),
    sa.Column('generator_retirement_date', sa.Date(), nullable=True, comment='Date of the scheduled or effected retirement of the generator.'),
    sa.Column('latitude', sa.Float(), nullable=True, comment="Latitude of the plant's location, in degrees."),
    sa.Column('longitude', sa.Float(), nullable=True, comment="Longitude of the plant's location, in degrees."),
    sa.Column('net_capacity_mwdc', sa.Float(), nullable=True, comment='Generation capacity in megawatts of direct current that is subject to a net metering agreement. Typically used for behind-the-meter solar PV.'),
    sa.Column('operational_status', sa.Text(), nullable=True, comment='The operating status of the asset. For generators this is based on which tab the generator was listed in in EIA 860.'),
    sa.Column('operational_status_code', sa.Text(), nullable=True, comment='The operating status of the asset.'),
    sa.Column('planned_derate_date', sa.Date(), nullable=True, comment='Planned effective month that the generator is scheduled to enter operation after the derate modification.'),
    sa.Column('planned_generator_retirement_date', sa.Date(), nullable=True, comment='Planned effective date of the scheduled retirement of the generator.'),
    sa.Column('planned_net_summer_capacity_derate_mw', sa.Float(), nullable=True, comment='Decrease in summer capacity expected to be realized from the derate modification to the equipment.'),
    sa.Column('planned_net_summer_capacity_uprate_mw', sa.Float(), nullable=True, comment='Increase in summer capacity expected to be realized from the modification to the equipment.'),
    sa.Column('planned_uprate_date', sa.Date(), nullable=True, comment='Planned effective date that the generator is scheduled to enter operation after the uprate modification.'),
    sa.Column('prime_mover_code', sa.Text(), nullable=True, comment='Code for the type of prime mover (e.g. CT, CG)'),
    sa.Column('state', sa.Text(), nullable=True, comment='Two letter US state abbreviation.'),
    sa.Column('summer_capacity_mw', sa.Float(), nullable=True, comment='The net summer capacity.'),
    sa.Column('technology_description', sa.Text(), nullable=True, comment='High level description of the technology used by the generator to produce electricity.'),
    sa.Column('winter_capacity_mw', sa.Float(), nullable=True, comment='The net winter capacity.'),
    sa.ForeignKeyConstraint(['data_maturity'], ['core_pudl__codes_data_maturities.code'], name=op.f('fk_core_eia860m__changelog_generators_data_maturity_core_pudl__codes_data_maturities')),
    sa.ForeignKeyConstraint(['energy_source_code_1'], ['core_eia__codes_energy_sources.code'], name=op.f('fk_core_eia860m__changelog_generators_energy_source_code_1_core_eia__codes_energy_sources')),
    sa.ForeignKeyConstraint(['operational_status_code'], ['core_eia__codes_operational_status.code'], name=op.f('fk_core_eia860m__changelog_generators_operational_status_code_core_eia__codes_operational_status')),
    sa.ForeignKeyConstraint(['prime_mover_code'], ['core_eia__codes_prime_movers.code'], name=op.f('fk_core_eia860m__changelog_generators_prime_mover_code_core_eia__codes_prime_movers')),
    sa.PrimaryKeyConstraint('plant_id_eia', 'generator_id', 'report_date', name=op.f('pk_core_eia860m__changelog_generators'))
    )
    op.drop_table('core_eia860m__monthly_generators_changelog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_eia860m__monthly_generators_changelog',
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('valid_till_date', sa.DATE(), nullable=True),
    sa.Column('plant_id_eia', sa.INTEGER(), nullable=False),
    sa.Column('plant_name_eia', sa.TEXT(), nullable=True),
    sa.Column('utility_id_eia', sa.INTEGER(), nullable=True),
    sa.Column('utility_name_eia', sa.TEXT(), nullable=True),
    sa.Column('generator_id', sa.TEXT(), nullable=False),
    sa.Column('capacity_mw', sa.FLOAT(), nullable=True),
    sa.Column('county', sa.TEXT(), nullable=True),
    sa.Column('current_planned_generator_operating_date', sa.DATE(), nullable=True),
    sa.Column('data_maturity', sa.TEXT(), nullable=True),
    sa.Column('energy_source_code_1', sa.TEXT(), nullable=True),
    sa.Column('energy_storage_capacity_mwh', sa.FLOAT(), nullable=True),
    sa.Column('fuel_type_code_pudl', sa.VARCHAR(length=7), nullable=True),
    sa.Column('generator_retirement_date', sa.DATE(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('net_capacity_mwdc', sa.FLOAT(), nullable=True),
    sa.Column('operational_status', sa.TEXT(), nullable=True),
    sa.Column('operational_status_code', sa.TEXT(), nullable=True),
    sa.Column('planned_derate_date', sa.DATE(), nullable=True),
    sa.Column('planned_generator_retirement_date', sa.DATE(), nullable=True),
    sa.Column('planned_net_summer_capacity_derate_mw', sa.FLOAT(), nullable=True),
    sa.Column('planned_net_summer_capacity_uprate_mw', sa.FLOAT(), nullable=True),
    sa.Column('planned_uprate_date', sa.DATE(), nullable=True),
    sa.Column('prime_mover_code', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('summer_capacity_mw', sa.FLOAT(), nullable=True),
    sa.Column('technology_description', sa.TEXT(), nullable=True),
    sa.Column('winter_capacity_mw', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['data_maturity'], ['core_pudl__codes_data_maturities.code'], name='fk_core_eia860m__monthly_generators_changelog_data_maturity_core_pudl__codes_data_maturities'),
    sa.ForeignKeyConstraint(['energy_source_code_1'], ['core_eia__codes_energy_sources.code'], name='fk_core_eia860m__monthly_generators_changelog_energy_source_code_1_core_eia__codes_energy_sources'),
    sa.ForeignKeyConstraint(['operational_status_code'], ['core_eia__codes_operational_status.code'], name='fk_core_eia860m__monthly_generators_changelog_operational_status_code_core_eia__codes_operational_status'),
    sa.ForeignKeyConstraint(['prime_mover_code'], ['core_eia__codes_prime_movers.code'], name='fk_core_eia860m__monthly_generators_changelog_prime_mover_code_core_eia__codes_prime_movers'),
    sa.PrimaryKeyConstraint('plant_id_eia', 'generator_id', 'report_date', name='pk_core_eia860m__monthly_generators_changelog')
    )
    op.drop_table('core_eia860m__changelog_generators')
    # ### end Alembic commands ###
