"""add ferc1 transmission materials and types

Revision ID: a83ab61fa2e0
Revises: 94ea5d97d9ec
Create Date: 2026-02-18 16:11:41.171636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83ab61fa2e0'
down_revision = '94ea5d97d9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_ferc1__yearly_transmission_lines_sched422', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting_structure_type_original', sa.Text(), nullable=True, comment='Original unstructured value for the supporting structure type from the source data. This column preserves the raw value for user interpretation when the categorized columns are ambiguous or contain multiple structure types/materials.'))
        batch_op.add_column(sa.Column('supporting_structure_material', sa.Enum('steel', 'wood', 'concrete'), nullable=True, comment='Material used in the supporting structure for the transmission line. Categorized values: steel, wood, concrete.'))
        batch_op.alter_column('supporting_structure_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pole', 'h_frame', 'tower', 'underground'),
               existing_nullable=True)

    with op.batch_alter_table('out_ferc1__yearly_transmission_lines_sched422', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supporting_structure_type_original', sa.Text(), nullable=True, comment='Original unstructured value for the supporting structure type from the source data. This column preserves the raw value for user interpretation when the categorized columns are ambiguous or contain multiple structure types/materials.'))
        batch_op.add_column(sa.Column('supporting_structure_material', sa.Enum('steel', 'wood', 'concrete'), nullable=True, comment='Material used in the supporting structure for the transmission line. Categorized values: steel, wood, concrete.'))
        batch_op.alter_column('supporting_structure_type',
               existing_type=sa.TEXT(),
               type_=sa.Enum('pole', 'h_frame', 'tower', 'underground'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_ferc1__yearly_transmission_lines_sched422', schema=None) as batch_op:
        batch_op.alter_column('supporting_structure_type',
               existing_type=sa.Enum('pole', 'h_frame', 'tower', 'underground'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('supporting_structure_material')
        batch_op.drop_column('supporting_structure_type_original')

    with op.batch_alter_table('core_ferc1__yearly_transmission_lines_sched422', schema=None) as batch_op:
        batch_op.alter_column('supporting_structure_type',
               existing_type=sa.Enum('pole', 'h_frame', 'tower', 'underground'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('supporting_structure_material')
        batch_op.drop_column('supporting_structure_type_original')

    # ### end Alembic commands ###
