"""add core ex 21 ownership table

Revision ID: b0b3835f8f47
Revises: f6ca9e20e5b0
Create Date: 2025-03-06 21:22:59.514705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b3835f8f47'
down_revision = 'f6ca9e20e5b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__quarterly_exhibit_21_company_ownership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_company_central_index_key', sa.Text(), nullable=True, comment="Central index key (CIK) of the company's parent company."))
        batch_op.add_column(sa.Column('parent_company_name', sa.Text(), nullable=True, comment='Name of the parent company.'))
        batch_op.add_column(sa.Column('subsidiary_company_id_sec10k', sa.Text(), nullable=True, comment='ID for subsidiaries extracted from SEC 10k Ex. 21 attachments.'))
        batch_op.add_column(sa.Column('filing_date', sa.Date(), nullable=True, comment='Date filing was submitted, reported at a daily frequency.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__quarterly_exhibit_21_company_ownership', schema=None) as batch_op:
        batch_op.drop_column('filing_date')
        batch_op.drop_column('subsidiary_company_id_sec10k')
        batch_op.drop_column('parent_company_name')
        batch_op.drop_column('parent_company_central_index_key')

    # ### end Alembic commands ###
