"""EIA861 short form changes

Revision ID: b32efacaa609
Revises: 827e88186933
Create Date: 2024-06-14 22:24:46.115481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32efacaa609'
down_revision = '827e88186933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_eia861__yearly_short_form')
    with op.batch_alter_table('core_eia860__scd_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_metering', sa.Boolean(), nullable=True, comment='Did this plant have a net metering agreement in effect during the reporting year?  (Only displayed for facilities that report the sun or wind as an energy source). This field was only reported up until 2015'))
        batch_op.drop_column('has_net_metering')

    with op.batch_alter_table('core_eia861__yearly_demand_response_water_heater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_heater', sa.Integer(), nullable=True, comment="The number of grid-enabled water heaters added to the respondent's program this year - if the respondent has DSM program for grid-enabled water heaters (as defined by DOE’s Office of Energy Efficiency and Renewable Energy)."))
        batch_op.drop_column('num_water_heaters')

    with op.batch_alter_table('core_eia861__yearly_demand_side_management_misc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_responsive_programs', sa.Boolean(), nullable=True, comment='Whether the respondent operates any time-based rate programs (e.g., real-time pricing, critical peak pricing, variable peak pricing and time-of-use rates administered through a tariff).'))
        batch_op.drop_column('has_time_responsive_programs')

    with op.batch_alter_table('out_eia__yearly_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_metering', sa.Boolean(), nullable=True, comment='Did this plant have a net metering agreement in effect during the reporting year?  (Only displayed for facilities that report the sun or wind as an energy source). This field was only reported up until 2015'))
        batch_op.drop_column('has_net_metering')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_eia__yearly_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_net_metering', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('net_metering')

    with op.batch_alter_table('core_eia861__yearly_demand_side_management_misc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_time_responsive_programs', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('time_responsive_programs')

    with op.batch_alter_table('core_eia861__yearly_demand_response_water_heater', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_water_heaters', sa.INTEGER(), nullable=True))
        batch_op.drop_column('water_heater')

    with op.batch_alter_table('core_eia860__scd_plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_net_metering', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('net_metering')

    op.create_table('core_eia861__yearly_short_form',
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('utility_id_eia', sa.INTEGER(), nullable=False),
    sa.Column('utility_name_eia', sa.TEXT(), nullable=True),
    sa.Column('entity_type', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=False),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=False),
    sa.Column('sales_revenue', sa.FLOAT(), nullable=True),
    sa.Column('sales_mwh', sa.FLOAT(), nullable=True),
    sa.Column('customers', sa.FLOAT(), nullable=True),
    sa.Column('has_net_metering', sa.BOOLEAN(), nullable=True),
    sa.Column('has_demand_side_management', sa.BOOLEAN(), nullable=True),
    sa.Column('has_time_responsive_programs', sa.BOOLEAN(), nullable=True),
    sa.Column('has_green_pricing', sa.BOOLEAN(), nullable=True),
    sa.Column('data_maturity', sa.TEXT(), nullable=True),
    sa.Column('num_water_heaters', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['balancing_authority_code_eia'], ['core_eia__codes_balancing_authorities.code'], name='fk_core_eia861__yearly_short_form_balancing_authority_code_eia_core_eia__codes_balancing_authorities'),
    sa.ForeignKeyConstraint(['data_maturity'], ['core_pudl__codes_data_maturities.code'], name='fk_core_eia861__yearly_short_form_data_maturity_core_pudl__codes_data_maturities'),
    sa.ForeignKeyConstraint(['utility_id_eia'], ['core_eia__entity_utilities.utility_id_eia'], name='fk_core_eia861__yearly_short_form_utility_id_eia_core_eia__entity_utilities'),
    sa.PrimaryKeyConstraint('utility_id_eia', 'state', 'report_date', 'balancing_authority_code_eia', name='pk_core_eia861__yearly_short_form')
    )
    # ### end Alembic commands ###
