"""add pk to sec ownership tables

Revision ID: b6fb43ee8a4d
Revises: 9c99bff536d2
Create Date: 2025-05-14 23:23:24.592685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fb43ee8a4d'
down_revision = '9c99bff536d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_sec10k__quarterly_exhibit_21_company_ownership', schema=None) as batch_op:
        batch_op.alter_column('filename_sec10k',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subsidiary_company_id_sec10k',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('out_sec10k__parents_and_subsidiaries', schema=None) as batch_op:
        batch_op.alter_column('filename_sec10k',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('subsidiary_company_id_sec10k',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_sec10k__parents_and_subsidiaries', schema=None) as batch_op:
        batch_op.alter_column('subsidiary_company_id_sec10k',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('filename_sec10k',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('core_sec10k__quarterly_exhibit_21_company_ownership', schema=None) as batch_op:
        batch_op.alter_column('subsidiary_company_id_sec10k',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('filename_sec10k',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
