"""Add eia930 make hourly tables parquet only

Revision ID: b9a189353dfc
Revises: 31ebdcf128b3
Create Date: 2024-04-28 14:24:18.911066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a189353dfc'
down_revision = '31ebdcf128b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_eia930__hourly_balancing_authority_subregion_demand')
    op.drop_table('core_eia930__hourly_balancing_authority_interchange')
    op.drop_table('out_ferc714__hourly_planning_area_demand')
    op.drop_table('core_eia930__hourly_balancing_authority_operations')
    op.drop_table('out_gridpathratoolkit__hourly_available_capacity_factor')
    op.drop_table('core_eia930__hourly_balancing_authority_net_generation_by_energy_source')
    op.drop_table('out_ferc714__hourly_estimated_state_demand')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('out_ferc714__hourly_estimated_state_demand',
    sa.Column('state_id_fips', sa.TEXT(), nullable=False),
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('demand_mwh', sa.FLOAT(), nullable=True),
    sa.Column('scaled_demand_mwh', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('state_id_fips', 'datetime_utc', name='pk_out_ferc714__hourly_estimated_state_demand')
    )
    op.create_table('core_eia930__hourly_balancing_authority_net_generation_by_energy_source',
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=False),
    sa.Column('generation_energy_source', sa.VARCHAR(length=7), nullable=False),
    sa.Column('net_generation_reported_mwh', sa.FLOAT(), nullable=True),
    sa.Column('net_generation_adjusted_mwh', sa.FLOAT(), nullable=True),
    sa.Column('net_generation_imputed_mwh', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['balancing_authority_code_eia'], ['core_eia__codes_balancing_authorities.code'], name='fk_core_eia930__hourly_balancing_authority_net_generation_by_energy_source_balancing_authority_code_eia_core_eia__codes_balancing_authorities'),
    sa.PrimaryKeyConstraint('datetime_utc', 'balancing_authority_code_eia', 'generation_energy_source', name='pk_core_eia930__hourly_balancing_authority_net_generation_by_energy_source')
    )
    op.create_table('out_gridpathratoolkit__hourly_available_capacity_factor',
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('aggregation_group', sa.TEXT(), nullable=False),
    sa.Column('capacity_factor', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('datetime_utc', 'aggregation_group', name='pk_out_gridpathratoolkit__hourly_available_capacity_factor')
    )
    op.create_table('core_eia930__hourly_balancing_authority_operations',
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=False),
    sa.Column('net_generation_reported_mwh', sa.FLOAT(), nullable=True),
    sa.Column('net_generation_adjusted_mwh', sa.FLOAT(), nullable=True),
    sa.Column('net_generation_imputed_mwh', sa.FLOAT(), nullable=True),
    sa.Column('interchange_reported_mwh', sa.FLOAT(), nullable=True),
    sa.Column('interchange_adjusted_mwh', sa.FLOAT(), nullable=True),
    sa.Column('interchange_imputed_mwh', sa.FLOAT(), nullable=True),
    sa.Column('demand_reported_mwh', sa.FLOAT(), nullable=True),
    sa.Column('demand_adjusted_mwh', sa.FLOAT(), nullable=True),
    sa.Column('demand_imputed_mwh', sa.FLOAT(), nullable=True),
    sa.Column('demand_forecast_mwh', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['balancing_authority_code_eia'], ['core_eia__codes_balancing_authorities.code'], name='fk_core_eia930__hourly_balancing_authority_operations_balancing_authority_code_eia_core_eia__codes_balancing_authorities'),
    sa.PrimaryKeyConstraint('datetime_utc', 'balancing_authority_code_eia', name='pk_core_eia930__hourly_balancing_authority_operations')
    )
    op.create_table('out_ferc714__hourly_planning_area_demand',
    sa.Column('respondent_id_ferc714', sa.INTEGER(), nullable=False),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=19), nullable=True),
    sa.Column('demand_mwh', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['respondent_id_ferc714'], ['core_ferc714__respondent_id.respondent_id_ferc714'], name='fk_out_ferc714__hourly_planning_area_demand_respondent_id_ferc714_core_ferc714__respondent_id'),
    sa.PrimaryKeyConstraint('respondent_id_ferc714', 'datetime_utc', name='pk_out_ferc714__hourly_planning_area_demand')
    )
    op.create_table('core_eia930__hourly_balancing_authority_interchange',
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=False),
    sa.Column('balancing_authority_code_adjacent_eia', sa.TEXT(), nullable=False),
    sa.Column('interchange_reported_mwh', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['balancing_authority_code_adjacent_eia'], ['core_eia__codes_balancing_authorities.code'], name='fk_core_eia930__hourly_balancing_authority_interchange_balancing_authority_code_adjacent_eia_core_eia__codes_balancing_authorities'),
    sa.ForeignKeyConstraint(['balancing_authority_code_eia'], ['core_eia__codes_balancing_authorities.code'], name='fk_core_eia930__hourly_balancing_authority_interchange_balancing_authority_code_eia_core_eia__codes_balancing_authorities'),
    sa.PrimaryKeyConstraint('datetime_utc', 'balancing_authority_code_eia', 'balancing_authority_code_adjacent_eia', name='pk_core_eia930__hourly_balancing_authority_interchange')
    )
    op.create_table('core_eia930__hourly_balancing_authority_subregion_demand',
    sa.Column('datetime_utc', sa.DATETIME(), nullable=False),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=False),
    sa.Column('balancing_authority_subregion_code_eia', sa.VARCHAR(length=4), nullable=False),
    sa.Column('demand_reported_mwh', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['balancing_authority_code_eia', 'balancing_authority_subregion_code_eia'], ['core_eia__codes_balancing_authority_subregions.balancing_authority_code_eia', 'core_eia__codes_balancing_authority_subregions.balancing_authority_subregion_code_eia'], name='fk_core_eia930__hourly_balancing_authority_subregion_demand_balancing_authority_code_eia_core_eia__codes_balancing_authority_subregions'),
    sa.PrimaryKeyConstraint('datetime_utc', 'balancing_authority_code_eia', 'balancing_authority_subregion_code_eia', name='pk_core_eia930__hourly_balancing_authority_subregion_demand')
    )
    # ### end Alembic commands ###
