"""Add moar cool rus7 tables

Revision ID: bf23373e2b4a
Revises: dcbe4c9e66d4
Create Date: 2026-01-26 15:25:48.062115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf23373e2b4a'
down_revision = 'dcbe4c9e66d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__yearly_energy_efficiency',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('customer_class', sa.Enum('public_other', 'other_electric', 'public_street_lighting', 'irrigation', 'sales_for_resale_other', 'commercial_and_industrial_small', 'residential_excluding_seasonal', 'commercial_and_industrial_large', 'residential_seasonal', 'transmission', 'total', 'sales_for_resale_rus_borrowers'), nullable=False, comment='High level categorization of customer type.'),
    sa.Column('date_range', sa.Enum('ytd', 'report_year', 'avg', 'ytd_budget', 'december', 'cumulative', 'new_in_report_year', 'report_month'), nullable=False, comment="The date range that any given record pertains to. Ex: 'december' implies that this record covers the month of December only, while 'avg' implies this record pertains to the average of the reporting period."),
    sa.Column('customers_num', sa.Float(), nullable=True, comment='Number of customers.'),
    sa.Column('invested', sa.Integer(), nullable=True, comment='The amount of money invested.'),
    sa.Column('savings_mmbtu', sa.Float(), nullable=True, comment='The estimated amount of energy savings from energy efficiency programs. Warning: We found values much larger than expected that we have not yet cleaned - this is likely a reporting unit error.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'customer_class', 'date_range', name=op.f('pk_core_rus7__yearly_energy_efficiency'))
    )
    op.create_table('core_rus7__yearly_investments',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('investment_description', sa.Text(), nullable=True, comment='Description of investment. This is a free-form text field and thus contains a wide variety of values.'),
    sa.Column('investment_type_code', sa.Integer(), nullable=True, comment='Investment type code.'),
    sa.Column('included_investments', sa.Float(), nullable=True, comment='Included investment.'),
    sa.Column('excluded_investments', sa.Float(), nullable=True, comment='Excluded investment.'),
    sa.Column('income_or_loss', sa.Float(), nullable=True, comment='Income or loss from investment.'),
    sa.Column('is_rural_development_investment', sa.Boolean(), nullable=True, comment='Whether or not the investment is Rural Development.')
    )
    op.create_table('core_rus7__yearly_long_term_debt',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('debt_description', sa.Text(), nullable=True, comment='Description of debt or loan. On the original form, there are nine provided descriptions and a section to add other free-form descriptions.'),
    sa.Column('balance_end_of_report_year', sa.Float(), nullable=True, comment='Loan or debt balance at end of report year.'),
    sa.Column('loan_interest', sa.Float(), nullable=True, comment='Loan or debt interest billed during this report year.'),
    sa.Column('loan_principal', sa.Float(), nullable=True, comment='Loan or debt principal billed during this report year.'),
    sa.Column('loan_total', sa.Float(), nullable=True, comment='Loan or debt total billed during this report year.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', name=op.f('pk_core_rus7__yearly_long_term_debt'))
    )
    op.create_table('core_rus7__yearly_patronage_capital',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('patronage_type', sa.Enum('total_received', 'distributions_special_retirements', 'received_supplier_of_electric_power', 'distributions_general_retirements', 'total_distributions_retirements', 'received_lenders_of_electric_power'), nullable=False, comment='Type of patronage capital distributed or received.'),
    sa.Column('patronage_report_year', sa.Float(), nullable=True, comment='Amount of patronage distributed or received within report year.'),
    sa.Column('patronage_cumulative', sa.Float(), nullable=True, comment='Amount of patronage distributed or received cumulatively. Received patronage capital is notreported cumulatively and thus will be null.'),
    sa.Column('is_total', sa.Boolean(), nullable=True, comment='Whether or not this record represents a total.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'patronage_type', name=op.f('pk_core_rus7__yearly_patronage_capital'))
    )
    op.create_table('core_rus7__yearly_power_requirements',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('electric_sales_revenue', sa.Integer(), nullable=True, comment='Total Revenue Received From Sales of Electric Energy. Total of lines 1c thru 9c on the original form.'),
    sa.Column('electric_sales_mwh', sa.Float(), nullable=True, comment='Total MWh Sold to electric sales. Total of lines 1b thru 9b on the original form.'),
    sa.Column('transmission_revenue', sa.Integer(), nullable=True, comment='Transmission revenue.'),
    sa.Column('other_electric_revenue', sa.Integer(), nullable=True, comment='Other electric revenue - other than electric_sales_revenue.'),
    sa.Column('own_use_mwh', sa.Float(), nullable=True, comment='The electricity in kWh used internally.'),
    sa.Column('purchased_mwh', sa.Float(), nullable=True, comment='The total electricity purchased.'),
    sa.Column('generated_mwh', sa.Float(), nullable=True, comment='The total electricity generated.'),
    sa.Column('purchases_and_generation_cost', sa.Integer(), nullable=True, comment='The cost of purchases and generation of electricity.'),
    sa.Column('interchange_mwh', sa.Float(), nullable=True, comment='The net interchange of electricity..'),
    sa.Column('peak_mw', sa.Float(), nullable=True, comment='The peak system kWh - the sum of all MW.'),
    sa.Column('is_peak_coincident', sa.Integer(), nullable=True, comment='Whether or not the peak_kw is coincident or non-coincident peak.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', name=op.f('pk_core_rus7__yearly_power_requirements'))
    )
    op.create_table('core_rus7__yearly_power_requirements_electric_customers',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('customer_class', sa.Enum('public_other', 'other_electric', 'public_street_lighting', 'irrigation', 'sales_for_resale_other', 'commercial_and_industrial_small', 'residential_excluding_seasonal', 'commercial_and_industrial_large', 'residential_seasonal', 'transmission', 'total', 'sales_for_resale_rus_borrowers'), nullable=False, comment='High level categorization of customer type.'),
    sa.Column('date_range', sa.Enum('ytd', 'report_year', 'avg', 'ytd_budget', 'december', 'cumulative', 'new_in_report_year', 'report_month'), nullable=False, comment="The date range that any given record pertains to. Ex: 'december' implies that this record covers the month of December only, while 'avg' implies this record pertains to the average of the reporting period."),
    sa.Column('customers_num', sa.Float(), nullable=True, comment='Number of customers.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'customer_class', 'date_range', name=op.f('pk_core_rus7__yearly_power_requirements_electric_customers'))
    )
    op.create_table('core_rus7__yearly_power_requirements_electric_sales',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('customer_class', sa.Enum('public_other', 'other_electric', 'public_street_lighting', 'irrigation', 'sales_for_resale_other', 'commercial_and_industrial_small', 'residential_excluding_seasonal', 'commercial_and_industrial_large', 'residential_seasonal', 'transmission', 'total', 'sales_for_resale_rus_borrowers'), nullable=False, comment='High level categorization of customer type.'),
    sa.Column('sales_mwh', sa.Float(), nullable=True, comment='Quantity of electricity sold in MWh.'),
    sa.Column('revenue', sa.Float(), nullable=True, comment='Amount of revenue.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'customer_class', name=op.f('pk_core_rus7__yearly_power_requirements_electric_sales'))
    )
    op.create_table('core_rus7__yearly_statement_of_operations',
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=False, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('statement_type', sa.Enum('operating_revenue', 'patronage_and_operating_margins', 'opex', 'electric_service_expense'), nullable=True, comment='High level section from the statement of operations table. Most of these types have subcomponents broken out in the ``statement_item_type`` column.'),
    sa.Column('statement_item_type', sa.Enum('interest_long_term_debt', 'total_minus', 'operating_revenue', 'interest_other', 'customer_service', 'distribution_operation', 'admin', 'distribution_maintenance', 'regional_market', 'purchased_power', 'tax_property', 'total', 'other_deductions', 'power_production', 'interest_charged_to_construction', 'sales', 'tax_other', 'transmission', 'customer_accounts', 'deprecation'), nullable=False, comment='Type of item from the statement of operations.'),
    sa.Column('date_range', sa.Enum('ytd', 'report_year', 'avg', 'ytd_budget', 'december', 'cumulative', 'new_in_report_year', 'report_month'), nullable=False, comment="The date range that any given record pertains to. Ex: 'december' implies that this record covers the month of December only, while 'avg' implies this record pertains to the average of the reporting period."),
    sa.Column('amount', sa.Float(), nullable=True, comment='Reported amount of dollars. This could be a balance or a change in value.'),
    sa.PrimaryKeyConstraint('report_date', 'borrower_id_rus', 'statement_item_type', 'date_range', name=op.f('pk_core_rus7__yearly_statement_of_operations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_rus7__yearly_statement_of_operations')
    op.drop_table('core_rus7__yearly_power_requirements_electric_sales')
    op.drop_table('core_rus7__yearly_power_requirements_electric_customers')
    op.drop_table('core_rus7__yearly_power_requirements')
    op.drop_table('core_rus7__yearly_patronage_capital')
    op.drop_table('core_rus7__yearly_long_term_debt')
    op.drop_table('core_rus7__yearly_investments')
    op.drop_table('core_rus7__yearly_energy_efficiency')
    # ### end Alembic commands ###
