"""Remove borrower_name_rus from core tables

Revision ID: bf8ca670d8ec
Revises: 5a68d776c5a9
Create Date: 2026-03-10 13:00:17.576074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8ca670d8ec'
down_revision = '5a68d776c5a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rus12__yearly_external_financial_risk_ratio', schema=None) as batch_op:
        batch_op.drop_column('borrower_name_rus')

    with op.batch_alter_table('core_rus12__yearly_investments', schema=None) as batch_op:
        batch_op.drop_column('borrower_name_rus')

    with op.batch_alter_table('core_rus7__yearly_external_financial_risk_ratio', schema=None) as batch_op:
        batch_op.drop_column('borrower_name_rus')

    with op.batch_alter_table('core_rus7__yearly_loans', schema=None) as batch_op:
        batch_op.drop_column('borrower_name_rus')

    with op.batch_alter_table('core_rus7__yearly_long_term_leases', schema=None) as batch_op:
        batch_op.drop_column('borrower_name_rus')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rus7__yearly_long_term_leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name_rus', sa.TEXT(), nullable=True))

    with op.batch_alter_table('core_rus7__yearly_loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name_rus', sa.TEXT(), nullable=True))

    with op.batch_alter_table('core_rus7__yearly_external_financial_risk_ratio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name_rus', sa.TEXT(), nullable=True))

    with op.batch_alter_table('core_rus12__yearly_investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name_rus', sa.TEXT(), nullable=True))

    with op.batch_alter_table('core_rus12__yearly_external_financial_risk_ratio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_name_rus', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
