"""Add PHMSA install decade table

Revision ID: c0a780b47bdc
Revises: 9a8d47bd495e
Create Date: 2026-07-31 10:23:29.928192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a780b47bdc'
down_revision = '9a8d47bd495e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_phmsagas__yearly_distribution_by_install_decade',
    sa.Column('report_id', sa.Integer(), nullable=False, comment='Report number of the PHMSA Gas utility submission.'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Date reported.'),
    sa.Column('operator_id_phmsa', sa.Integer(), nullable=False, comment='PHMSA unique operator ID. A value of zero represents an unknown operator ID.'),
    sa.Column('commodity', sa.Enum('Natural Gas', 'Propane Gas', 'Landfill Gas', 'Synthetic Gas', 'Hydrogen Gas', 'Nitrogen Gas', 'unknown'), nullable=True, comment='The type of gas delivered by the distribution pipeline.'),
    sa.Column('operating_state', sa.Text(), nullable=False, comment='State that the distribution utility is reporting for. Prior to 2004, this may be a list of states.'),
    sa.Column('install_decade', sa.Text(), nullable=False, comment='The decade the distribution pipeline was installed.'),
    sa.Column('mains_miles', sa.Float(), nullable=True, comment='The miles of mains distribution pipeline.'),
    sa.Column('services', sa.Integer(), nullable=True, comment='Number of services in system at end of year.'),
    sa.ForeignKeyConstraint(['report_id', 'report_date', 'operator_id_phmsa'], ['core_phmsagas__yearly_distribution_operators.report_id', 'core_phmsagas__yearly_distribution_operators.report_date', 'core_phmsagas__yearly_distribution_operators.operator_id_phmsa'], name=op.f('fk_core_phmsagas__yearly_distribution_by_install_decade_report_id_core_phmsagas__yearly_distribution_operators')),
    sa.PrimaryKeyConstraint('report_id', 'report_date', 'operator_id_phmsa', 'operating_state', 'install_decade', name=op.f('pk_core_phmsagas__yearly_distribution_by_install_decade'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_phmsagas__yearly_distribution_by_install_decade')
    # ### end Alembic commands ###
