"""Update state encoding for FERC 714 and SEC 10k

Revision ID: cccad392bec1
Revises: 1aa58750654a
Create Date: 2025-02-17 11:18:49.976951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccad392bec1'
down_revision = '1aa58750654a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_out_ferc714__respondents_with_fips')
    with op.batch_alter_table('core_eia860__scd_generators_multifuel', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.TEXT(),
               type_=sa.Enum('NY', 'IA', 'MN', 'CA', 'MI', 'AL', 'ID', 'WY', 'RI', 'ND', 'OR', 'IN', 'MT', 'WI', 'OK', 'FL', 'VA', 'AR', 'ME', 'NH', 'WV', 'TN', 'AK', 'LA', 'MO', 'GA', 'SC', 'NE', 'OH', 'MA', 'MS', 'CO', 'NM', 'KS', 'MD', 'NV', 'TX', 'VT', 'KY', 'WA', 'SD', 'DE', 'HI', 'UT', 'IL', 'PA', 'CT', 'NJ', 'NC', 'AZ'),
               existing_nullable=True)

    with op.batch_alter_table('out_sec10k__parents_and_subsidiaries', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.TEXT(),
               type_=sa.Enum('NY', 'IA', 'MN', 'CA', 'MI', 'AL', 'ID', 'WY', 'RI', 'ND', 'OR', 'IN', 'MT', 'WI', 'OK', 'FL', 'VA', 'AR', 'ME', 'NH', 'WV', 'TN', 'AK', 'LA', 'MO', 'GA', 'SC', 'NE', 'OH', 'MA', 'MS', 'CO', 'NM', 'KS', 'MD', 'NV', 'TX', 'VT', 'KY', 'WA', 'SD', 'DE', 'HI', 'UT', 'IL', 'PA', 'CT', 'NJ', 'NC', 'AZ'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_sec10k__parents_and_subsidiaries', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('NY', 'IA', 'MN', 'CA', 'MI', 'AL', 'ID', 'WY', 'RI', 'ND', 'OR', 'IN', 'MT', 'WI', 'OK', 'FL', 'VA', 'AR', 'ME', 'NH', 'WV', 'TN', 'AK', 'LA', 'MO', 'GA', 'SC', 'NE', 'OH', 'MA', 'MS', 'CO', 'NM', 'KS', 'MD', 'NV', 'TX', 'VT', 'KY', 'WA', 'SD', 'DE', 'HI', 'UT', 'IL', 'PA', 'CT', 'NJ', 'NC', 'AZ'),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('core_eia860__scd_generators_multifuel', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('NY', 'IA', 'MN', 'CA', 'MI', 'AL', 'ID', 'WY', 'RI', 'ND', 'OR', 'IN', 'MT', 'WI', 'OK', 'FL', 'VA', 'AR', 'ME', 'NH', 'WV', 'TN', 'AK', 'LA', 'MO', 'GA', 'SC', 'NE', 'OH', 'MA', 'MS', 'CO', 'NM', 'KS', 'MD', 'NV', 'TX', 'VT', 'KY', 'WA', 'SD', 'DE', 'HI', 'UT', 'IL', 'PA', 'CT', 'NJ', 'NC', 'AZ'),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_out_ferc714__respondents_with_fips',
    sa.Column('eia_code', sa.INTEGER(), nullable=True),
    sa.Column('respondent_type', sa.VARCHAR(length=19), nullable=True),
    sa.Column('respondent_id_ferc714', sa.INTEGER(), nullable=True),
    sa.Column('respondent_name_ferc714', sa.TEXT(), nullable=True),
    sa.Column('report_date', sa.DATE(), nullable=True),
    sa.Column('balancing_authority_id_eia', sa.INTEGER(), nullable=True),
    sa.Column('balancing_authority_code_eia', sa.TEXT(), nullable=True),
    sa.Column('balancing_authority_name_eia', sa.TEXT(), nullable=True),
    sa.Column('utility_id_eia', sa.INTEGER(), nullable=True),
    sa.Column('utility_name_eia', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('county', sa.TEXT(), nullable=True),
    sa.Column('state_id_fips', sa.TEXT(), nullable=True),
    sa.Column('county_id_fips', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['respondent_id_ferc714'], ['core_pudl__assn_ferc714_pudl_respondents.respondent_id_ferc714'], name='fk_out_ferc714__respondents_with_fips_respondent_id_ferc714_core_pudl__assn_ferc714_pudl_respondents')
    )
    # ### end Alembic commands ###
