"""rus

Revision ID: d746cb9cf646
Revises: a4e2078b82ee
Create Date: 2026-03-03 12:39:28.360241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd746cb9cf646'
down_revision = 'a4e2078b82ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__yearly_loans',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('lending_organization', sa.Text(), nullable=True, comment='The organization that provided a lease or loan.'),
    sa.Column('loan_balance', sa.Float(), nullable=True, comment='The amount of money still owned on a loan at the end of the reporting year.'),
    sa.Column('loan_maturity_date', sa.Date(), nullable=True, comment='The date on which a loan is scheduled to be fully paid.'),
    sa.Column('loan_original_amount', sa.Float(), nullable=True, comment='The original amount of a loan.'),
    sa.Column('for_rural_development', sa.Boolean(), nullable=True, comment='Whether or not the investment or loan is for rural development. This includes investments in any/all types of projects or products that were made to improve the economy and/or quality of life in the specified area.'),
    sa.Column('is_loan_guarantee', sa.Boolean(), nullable=True, comment='Indicates whether a loan is from a private lender and the funding will be provided by the federal government if the borrower defaults.')
    )
    op.create_table('core_rus7__yearly_long_term_leases',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('lending_organization', sa.Text(), nullable=True, comment='The organization that provided a lease or loan.'),
    sa.Column('property_type', sa.Text(), nullable=True, comment='The type of property leased.'),
    sa.Column('rental_cost_ytd', sa.Float(), nullable=True, comment='Year-to-date rental cost for leased property.')
    )
    op.create_table('core_rus12__yearly_investments',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('borrower_name_rus', sa.Text(), nullable=True, comment='The name of the RUS (Rural Utilities Service) borrower.'),
    sa.Column('investment_description', sa.Text(), nullable=True, comment='Description of investment. This is a free-form text field and thus contains a wide variety of values.'),
    sa.Column('investment_type_code', sa.Integer(), nullable=True, comment='Investment type code.'),
    sa.Column('included_investments', sa.Float(), nullable=True, comment='Included investment.'),
    sa.Column('excluded_investments', sa.Float(), nullable=True, comment='Excluded investment.'),
    sa.Column('income_or_loss', sa.Float(), nullable=True, comment='Income or loss from investment.'),
    sa.Column('for_rural_development', sa.Boolean(), nullable=True, comment='Whether or not the investment or loan is for rural development. This includes investments in any/all types of projects or products that were made to improve the economy and/or quality of life in the specified area.'),
    sa.ForeignKeyConstraint(['investment_type_code'], ['core_rus7__codes_investment_types.code'], name=op.f('fk_core_rus12__yearly_investments_investment_type_code_core_rus7__codes_investment_types'))
    )
    with op.batch_alter_table('core_rus12__yearly_loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lending_organization', sa.Text(), nullable=True, comment='The organization that provided a lease or loan.'))
        batch_op.add_column(sa.Column('is_loan_guarantee', sa.Boolean(), nullable=True, comment='Indicates whether a loan is from a private lender and the funding will be provided by the federal government if the borrower defaults.'))
        batch_op.drop_column('loan_organization')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_rus12__yearly_loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_organization', sa.TEXT(), nullable=True))
        batch_op.drop_column('is_loan_guarantee')
        batch_op.drop_column('lending_organization')

    op.drop_table('core_rus12__yearly_investments')
    op.drop_table('core_rus7__yearly_long_term_leases')
    op.drop_table('core_rus7__yearly_loans')
    # ### end Alembic commands ###
