"""add new ferc1 other reg assets

Revision ID: d85141a4eafc
Revises: 8ea3f44edf13
Create Date: 2026-04-13 16:54:57.931719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd85141a4eafc'
down_revision = '8ea3f44edf13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_ferc1__yearly_other_regulatory_assets_sched232',
    sa.Column('utility_id_ferc1', sa.Integer(), nullable=True, comment='PUDL-assigned utility ID, identifying a FERC1 utility. This is an auto-incremented ID and is not expected to be stable from year to year.'),
    sa.Column('report_year', sa.Integer(), nullable=True, comment='Four-digit year in which the data was reported.'),
    sa.Column('description', sa.Text(), nullable=True, comment='Free-form description and purpose of other regulatory assets.'),
    sa.Column('additional_description', sa.Text(), nullable=True, comment='Additional free-form description column. In most instances, the values in this column are exactly the same as the description column,but it differs from the standard description enough that we kept both columns.'),
    sa.Column('ending_balance', sa.Float(), nullable=True, comment='Account balance at end of year.'),
    sa.Column('starting_balance', sa.Float(), nullable=True, comment='Account balance at beginning of year.'),
    sa.Column('debits', sa.Float(), nullable=True, comment='The increase (decrease) during the period in the value of other assets resulting from the ratemaking actions of regulatory agencies.'),
    sa.Column('credits_written_off_recovered', sa.Float(), nullable=True, comment='Recovered amount of divestiture of other assets lacking physical substance resulting from the ratemaking actions of regulatory agencies.'),
    sa.Column('account_detail', sa.Text(), nullable=True, comment='Description of the account number credited from making debit adjustment to other regulatory liabilities.'),
    sa.ForeignKeyConstraint(['utility_id_ferc1'], ['core_pudl__assn_ferc1_pudl_utilities.utility_id_ferc1'], name=op.f('fk_core_ferc1__yearly_other_regulatory_assets_sched232_utility_id_ferc1_core_pudl__assn_ferc1_pudl_utilities'))
    )
    with op.batch_alter_table('core_ferc1__yearly_other_regulatory_liabilities_sched278', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_description', sa.Text(), nullable=True, comment='Additional free-form description column. In most instances, the values in this column are exactly the same as the description column,but it differs from the standard description enough that we kept both columns.'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_ferc1__yearly_other_regulatory_liabilities_sched278', schema=None) as batch_op:
        batch_op.drop_column('additional_description')

    op.drop_table('core_ferc1__yearly_other_regulatory_assets_sched232')
    # ### end Alembic commands ###
