"""add missing source_url field.

Revision ID: d9aa1864d5ec
Revises: 8340b4f2370a
Create Date: 2025-03-28 12:15:07.942124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9aa1864d5ec'
down_revision = '8340b4f2370a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filer_count', sa.Integer(), nullable=True, comment='A counter indicating which observation of company data within an SEC 10-K filing header the record pertains to.'))
        batch_op.add_column(sa.Column('business_street_address', sa.Text(), nullable=True, comment="Street address of the company's place of business."))
        batch_op.add_column(sa.Column('business_street_address_2', sa.Text(), nullable=True, comment="Second line of the street address of the company's place of business."))
        batch_op.add_column(sa.Column('business_city', sa.Text(), nullable=True, comment="City where the company's place of business is located."))
        batch_op.add_column(sa.Column('business_state', sa.Text(), nullable=True, comment="State where the company's place of business is located."))
        batch_op.add_column(sa.Column('business_zip_code', sa.Text(), nullable=True, comment="Zip code of the company's place of business."))
        batch_op.add_column(sa.Column('business_zip_code_4', sa.Text(), nullable=True, comment="Zip code suffix of the company's place of business."))
        batch_op.add_column(sa.Column('business_postal_code', sa.Text(), nullable=True, comment="Non-US postal code of the company's place of business."))
        batch_op.add_column(sa.Column('mail_street_address', sa.Text(), nullable=True, comment="Street portion of the company's for mailing address."))
        batch_op.add_column(sa.Column('mail_street_address_2', sa.Text(), nullable=True, comment="Second line of the street portion of the company's mailing address."))
        batch_op.add_column(sa.Column('mail_city', sa.Text(), nullable=True, comment="City of the company's mailing address."))
        batch_op.add_column(sa.Column('mail_state', sa.Text(), nullable=True, comment="State of the company's mailing address."))
        batch_op.add_column(sa.Column('mail_zip_code', sa.Text(), nullable=True, comment="Zip code of the company's mailing address."))
        batch_op.add_column(sa.Column('mail_zip_code_4', sa.Text(), nullable=True, comment="Zip code suffix of the company's mailing address."))
        batch_op.add_column(sa.Column('mail_postal_code', sa.Text(), nullable=True, comment="Non-US postal code of the company's mailing address."))
        batch_op.add_column(sa.Column('source_url', sa.Text(), nullable=True, comment='URL pointing to the original source of the data in the record.'))
        batch_op.add_column(sa.Column('filing_date', sa.Date(), nullable=True, comment='Date filing was submitted, reported at a daily frequency.'))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('address_2')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')
        batch_op.drop_column('name_change_date')
        batch_op.drop_column('zip_code_4')
        batch_op.drop_column('company_name_old')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('out_sec10k__quarterly_company_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name_old', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('zip_code_4', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('name_change_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('street_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.TEXT(), nullable=True))
        batch_op.drop_column('filing_date')
        batch_op.drop_column('source_url')
        batch_op.drop_column('mail_postal_code')
        batch_op.drop_column('mail_zip_code_4')
        batch_op.drop_column('mail_zip_code')
        batch_op.drop_column('mail_state')
        batch_op.drop_column('mail_city')
        batch_op.drop_column('mail_street_address_2')
        batch_op.drop_column('mail_street_address')
        batch_op.drop_column('business_postal_code')
        batch_op.drop_column('business_zip_code_4')
        batch_op.drop_column('business_zip_code')
        batch_op.drop_column('business_state')
        batch_op.drop_column('business_city')
        batch_op.drop_column('business_street_address_2')
        batch_op.drop_column('business_street_address')
        batch_op.drop_column('filer_count')

    # ### end Alembic commands ###
