"""update aeo schema

Revision ID: de3c08191d8a
Revises: 76397c4db652
Create Date: 2025-09-09 13:39:46.145012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3c08191d8a'
down_revision = '76397c4db652'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eiaaeo__yearly_projected_energy_use_by_sector_and_type', schema=None) as batch_op:
        batch_op.alter_column('energy_use_sector',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Enum('commercial_other', 'other', 'electric_power', 'transportation', 'commercial', 'residential', 'unspecified', 'industrial', 'industrial_hydrogen_production', 'total'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('core_eiaaeo__yearly_projected_energy_use_by_sector_and_type', schema=None) as batch_op:
        batch_op.alter_column('energy_use_sector',
               existing_type=sa.Enum('commercial_other', 'other', 'electric_power', 'transportation', 'commercial', 'residential', 'unspecified', 'industrial', 'industrial_hydrogen_production', 'total'),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
