"""Add rus7 energy_purchased table

Revision ID: e666ac483bb6
Revises: ac1dd74e5fd2
Create Date: 2026-03-16 17:53:13.992041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e666ac483bb6'
down_revision = 'ac1dd74e5fd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_rus7__yearly_energy_purchased',
    sa.Column('report_date', sa.Date(), nullable=True, comment='Date reported.'),
    sa.Column('borrower_id_rus', sa.Text(), nullable=True, comment="Unique identifier of RUS (Rural Utilities Service) borrower. These ID's are structured as: two character state acronyms followed by four digits."),
    sa.Column('purchased_mwh', sa.Float(), nullable=True, comment='The total electricity purchased.'),
    sa.Column('purchased_energy_cost_total', sa.Float(), nullable=True, comment='The total cost of purchased energy.'),
    sa.Column('average_energy_cost_cents_per_mwh', sa.Float(), nullable=True, comment='The average cost of fuel per MWh.'),
    sa.Column('wheeling_and_other_charges', sa.Float(), nullable=True, comment='The cost of wheeling and other charges or credits related to fuel. Included in the total cost.'),
    sa.Column('fuel_cost_adjustment', sa.Float(), nullable=True, comment="The variable fuel surcharge component of a distribution cooperative's wholesale purchased power bill, reflecting pass-through of actual fuel cost fluctuations from the supplying utility, reported separately from base power charges and wheeling costs. Included in the total cost."),
    sa.Column('fuel_type_code_rus', sa.Integer(), nullable=True, comment='Unique numeric identifier for RUS fuel types.'),
    sa.Column('is_eia_borrower', sa.Boolean(), nullable=True, comment='Whether the utility supplying energy to a RUS borrower is an EIA respondent.'),
    sa.Column('supplier_code_rus', sa.Text(), nullable=True, comment='Unique numeric identifier for the utility supplying energy to a RUS borrower.'),
    sa.Column('utility_name_eia', sa.Text(), nullable=True, comment='The name of the utility.'),
    sa.Column('comments', sa.Text(), nullable=True, comment='General comments field.'),
    sa.ForeignKeyConstraint(['borrower_id_rus'], ['core_rus7__entity_borrowers.borrower_id_rus'], name=op.f('fk_core_rus7__yearly_energy_purchased_borrower_id_rus_core_rus7__entity_borrowers'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_rus7__yearly_energy_purchased')
    # ### end Alembic commands ###
