version: 2
sources:
  - name: pudl
    tables:
      - name: core_ferc1__yearly_energy_sources_sched401
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_ferc1
                pk_table_name: source('pudl', 'core_pudl__assn_ferc1_pudl_utilities')
                pk_column_names:
                  - utility_id_ferc1
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_ferc1__yearly_energy_sources_sched401
                partition_expr: report_year
        columns:
          - name: utility_id_ferc1
          - name: report_year
          - name: energy_source_type
          - name: row_type_xbrl
          - name: energy_mwh
          - name: record_id
