version: 2
sources:
  - name: pudl
    tables:
      - name: core_pudl__assn_eia_pudl_utilities
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_pudl
                pk_table_name: source('pudl', 'core_pudl__entity_utilities_pudl')
                pk_column_names:
                  - utility_id_pudl
          - expect_columns_not_all_null
          - check_row_counts_per_partition
        columns:
          - name: utility_id_eia
            data_tests:
              - not_null
              - one_value_per_key:
                  arguments:
                    other_column_name: utility_id_pudl
          - name: utility_name_eia
          - name: utility_id_pudl
            data_tests:
              - not_null
