version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia860__assn_boiler_generator
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - boiler_generator_assn_type_code
                pk_table_name: source('pudl', 'core_eia__codes_boiler_generator_assn_types')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - steam_plant_type_code
                pk_table_name: source('pudl', 'core_eia__codes_steam_plant_types')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - data_maturity
                pk_table_name: source('pudl', 'core_pudl__codes_data_maturities')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                  - boiler_id
                  - report_date
                pk_table_name: source('pudl', 'core_eia860__scd_boilers')
                pk_column_names:
                  - plant_id_eia
                  - boiler_id
                  - report_date
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                  - generator_id
                  - report_date
                pk_table_name: source('pudl', 'core_eia860__scd_generators')
                pk_column_names:
                  - plant_id_eia
                  - generator_id
                  - report_date
          - expect_columns_not_all_null:
              arguments:
                row_conditions:
                  boiler_generator_assn_type_code: EXTRACT(year FROM report_date) BETWEEN 2009 AND 2012
                  steam_plant_type_code: EXTRACT(year FROM report_date) >= 2014
                  data_maturity: EXTRACT(year FROM report_date) >= 2009
          - check_row_counts_per_partition:
              arguments:
                table_name: core_eia860__assn_boiler_generator
                partition_expr: EXTRACT(YEAR FROM report_date)
          - expect_date_frequency_ratio:
              arguments:
                compare_model: source("pudl", "out_eia__yearly_generators")
                multiplier: 1
                date_column: report_date
        columns:
          - name: plant_id_eia
          - name: report_date
          - name: generator_id
          - name: boiler_id
          - name: unit_id_eia
          - name: unit_id_pudl
          - name: boiler_generator_assn_type_code
          - name: steam_plant_type_code
          - name: bga_source
          - name: data_maturity
