version: 2
sources:
  - name: pudl
    tables:
      - name: _core_eia__forensics_entity_resolution_utilities
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_eia
                  - report_date
                pk_table_name: source('pudl', 'core_eia860__scd_utilities')
                pk_column_names:
                  - utility_id_eia
                  - report_date
        columns:
          - name: utility_id_eia
          - name: report_date
          - name: valid_until_date
          - name: column_name
          - name: record_value
          - name: entity_occurrences
          - name: record_occurrences
          - name: consistent_rate
          - name: is_candidate
