version: 2
sources:
  - name: pudl
    tables:
      - name: core_eia176__yearly_gas_supply

        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_eia176__yearly_gas_supply
                partition_expr: "report_year"

        columns:
          - name: operator_id_eia
          - name: report_year
          - name: operating_state
          - name: natural_gas_production_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: synthetic_gas_production_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: underground_storage_withdrawals_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: lng_storage_withdrawals_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: above_ground_storage_withdrawals_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: receipts_from_state_or_us_border_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: total_citygate_receipts_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: citygate_receipts_sales_customers_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: citygate_receipts_transportation_customers_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: other_receipts_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: supplemental_gaseous_fuels_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: total_supply_mcf
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
