version: 2
sources:
  - name: pudl
    tables:
      - name: out_eia923__monthly_generation_fuel_by_generator_energy_source
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - energy_source_code
                pk_table_name: source('pudl', 'core_eia__codes_energy_sources')
                pk_column_names:
                  - code
          - foreign_key:
              arguments:
                fk_column_names:
                  - plant_id_eia
                  - generator_id
                pk_table_name: source('pudl', 'core_eia__entity_generators')
                pk_column_names:
                  - plant_id_eia
                  - generator_id
          - foreign_key:
              arguments:
                fk_column_names:
                  - prime_mover_code
                pk_table_name: source('pudl', 'core_eia__codes_prime_movers')
                pk_column_names:
                  - code
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: EXTRACT(YEAR FROM report_date)
          - expect_date_frequency_ratio:
              arguments:
                compare_model: source("pudl", "out_eia__yearly_generators")
                multiplier: 12
                date_column: report_date
                model_has_data_maturity: false
        columns:
          - name: report_date
          - name: plant_id_eia
          - name: generator_id
          - name: prime_mover_code
          - name: energy_source_code
          - name: energy_source_code_num
          - name: net_generation_mwh
          - name: fuel_consumed_mmbtu
          - name: fuel_consumed_for_electricity_mmbtu
