version: 2
sources:
  - name: pudl
    tables:
      - name: core_rus12__yearly_plant_operations_by_plant
        data_tests:
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                table_name: core_rus12__yearly_plant_operations_by_plant
                partition_expr: "EXTRACT(YEAR FROM report_date)"
          - dbt_utils.expression_is_true:
              arguments:
                expression: "(operating_hours_in_service + operating_hours_on_standby + operating_hours_out_of_service_scheduled + operating_hours_out_of_service_unscheduled) <= 8785"
              description: "Plants shouldn't report more hours across all fields than there are in a calendar year (8784 is a leap year, and we allow for rounding)."
        columns:
          - name: report_date
          - name: borrower_id_rus
          - name: borrower_name_rus
          - name: plant_name_rus
          - name: unit_id_rus
          - name: plant_type
          - name: capacity_mw
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: gross_generation_mwh
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: ownership_pct
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
              - dbt_expectations.expect_column_max_to_be_between:
                  arguments:
                    min_value: 100.0
          - name: is_partly_owned_by_borrower
          - name: fuel_consumption_coal_lbs
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
              - dbt_expectations.expect_column_max_to_be_between:
                  arguments:
                    min_value: 0.0
                    row_condition: plant_type NOT IN ('hydro', 'nuclear')
          - name: fuel_consumption_gas_cubic_feet
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
              - dbt_expectations.expect_column_max_to_be_between:
                  arguments:
                    min_value: 0.0
                    row_condition: plant_type NOT IN ('hydro', 'nuclear')
          - name: fuel_consumption_oil_gallons
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
              - dbt_expectations.expect_column_max_to_be_between:
                  arguments:
                    min_value: 0.0
                    row_condition: plant_type NOT IN ('hydro', 'nuclear')
          - name: fuel_consumption_other
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
              - dbt_expectations.expect_column_max_to_be_between:
                  arguments:
                    min_value: 0.0
                    row_condition: plant_type NOT IN ('hydro', 'nuclear')
          - name: operating_hours_in_service
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: operating_hours_on_standby
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: operating_hours_out_of_service_scheduled
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: operating_hours_out_of_service_unscheduled
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
          - name: times_started
            data_tests:
              - dbt_expectations.expect_column_min_to_be_between:
                  arguments:
                    min_value: 0.0
