name: build-deploy-docs

on:
  push:
    branches:
      - main
      - nightly
      - stable
    tags:
      - "v20*"
  workflow_dispatch:

permissions:
  contents: write

env:
  PUDL_OUTPUT: /home/runner/pudl-work/output/
  PUDL_INPUT: /home/runner/pudl-work/input/
  DAGSTER_HOME: /home/runner/pudl-work/dagster_home/

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    if: contains('refs/heads/main refs/heads/stable refs/heads/nightly', github.ref) || contains(github.ref, 'refs/tags/v20')
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pudl environment with pixi
        uses: prefix-dev/setup-pixi@v0.9.5
        with:
          locked: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Make input, output and dagster dirs
        run: mkdir -p ${{ env.PUDL_OUTPUT }} ${{ env.PUDL_INPUT}} ${{ env.DAGSTER_HOME }}

      - name: Compute version for switcher and destination directory
        run: |
          PUDL_VERSION_MATCH=${{ case(github.ref == 'refs/heads/main', 'latest', github.ref) }}
          echo PUDL_VERSION_MATCH=${PUDL_VERSION_MATCH##*/} > "$GITHUB_ENV"

      - name: Lint and build PUDL documentation with Sphinx
        run: |
          pixi run docs-build

      - name: Deploy to GitHub Pages at the appropriate version path
        if: ${{ env.PUDL_VERSION_MATCH != '' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          destination_dir: en/${{ env.PUDL_VERSION_MATCH }}
          user_name: "pudlbot"
          user_email: "pudl@catalyst.coop"
          exclude_assets: ".github,.doctrees,.buildinfo"
