---
name: zenodo-cache-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5" # Weekdays at midnight on MST
  pull_request:
    paths:
      - "src/pudl/package_data/settings/zenodo_dois.yml"

env:
  CLOUD_CACHE_PATH: s3://pudl.catalyst.coop/zenodo/
  PUDL_OUTPUT: ~/pudl-work/output
  PUDL_INPUT: ~/pudl-work/input/

jobs:
  zenodo-cache-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout desired branch
        uses: actions/checkout@v6

      - name: Install pudl environment using pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          locked: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Update AWS S3 cache with any new Zenodo archives
        run: |
          pixi run pudl_datastore --all --cloud-cache-path ${{ env.CLOUD_CACHE_PATH }} --bypass-local-cache --loglevel DEBUG

  zulip-notify:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: zenodo-cache-sync
    steps:
      - name: Notify Zulip of cache sync status
        uses: zulip/github-actions-zulip/send-message@v2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: "build-status-bot@catalyst-cooperative.zulipchat.com"
          organization-url: "https://catalyst-cooperative.zulipchat.com"
          type: "stream"
          to: "pudl-deployments"
          topic: "zenodo-cache-sync"
          content: >
            ${{ needs.zenodo-cache-sync.result }} === 'success' ? ':check:' : ${{ needs.zenodo-cache-sync.result }} === 'failure' ? ':x:' : ':warning:'
            Zenodo cache sync on `${{ github.ref_name }}`
            ${{ needs.zenodo-cache-sync.result }} === 'success' ? 'succeeded' : ${{ needs.zenodo-cache-sync.result }} === 'failure' ? 'failed' : 'warning'
            [GitHub Action logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
