version: 2
sources:
  - name: pudl
    tables:
      - name: core_ferc1__yearly_depreciation_summary_sched336
        data_tests:
          - foreign_key:
              arguments:
                fk_column_names:
                  - utility_id_ferc1
                pk_table_name: source('pudl', 'core_pudl__assn_ferc1_pudl_utilities')
                pk_column_names:
                  - utility_id_ferc1
          - expect_columns_not_all_null
          - check_row_counts_per_partition:
              arguments:
                partition_expr: report_year
        columns:
          - name: record_id
          - name: report_year
          - name: utility_id_ferc1
          - name: plant_function
          - name: ferc_account_label
          - name: ferc_account
          - name: dollar_value
          - name: utility_type
          - name: row_type_xbrl
